# Generated by Django 5.2.16 on 2026-07-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_alter_quotation_options_alter_salesinvoice_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quotationitem",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="quotation",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quotation",
            name="converted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quotation",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quotation",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DRAFT", "Draft"),
                    ("SENT", "Sent"),
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                    ("EXPIRED", "Expired"),
                    ("CONVERTED", "Converted"),
                ],
                default="DRAFT",
                max_length=30,
                null=True,
            ),
        ),
    ]
