# Generated by Django 5.2.16 on 2026-07-24 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
        ("sales", "0003_alter_quotationitem_options_quotation_accepted_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="possale",
            options={"ordering": ["-sale_datetime", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="possaleitem",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="pricelist",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="pricelistitem",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="salescreditnote",
            options={"ordering": ["-credit_date", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="salescreditnoteitem",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="salesinvoiceitem",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="salesorderitem",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="salespayment",
            options={"ordering": ["-payment_date", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="salesreport",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="salesreturn",
            options={"ordering": ["-return_date", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="salesreturnitem",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="possale",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="possale",
            name="void_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="possale",
            name="voided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salescreditnote",
            name="issued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salescreditnote",
            name="void_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salescreditnote",
            name="voided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="issued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="last_reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="voided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="fulfilled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesreturn",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesreturn",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_sales_returns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="salesreturn",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesreturn",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="possale",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("CASH", "Cash"), ("CARD", "Card"), ("SPLIT", "Split")],
                default="CASH",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="possale",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("DRAFT", "Draft"), ("PAID", "Paid"), ("VOID", "Void")],
                default="PAID",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pricelist",
            name="discount_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PERCENTAGE", "Percentage"),
                    ("FIXED", "Fixed"),
                    ("CUSTOM_PRICE", "Custom Price"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pricelist",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DRAFT", "Draft"),
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("EXPIRED", "Expired"),
                ],
                default="DRAFT",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="salescreditnote",
            name="reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RETURN_DAMAGED", "Return / Damaged Goods"),
                    ("PRICING_ERROR", "Pricing Error"),
                    ("DISCOUNT_ADJUSTMENT", "Discount Adjustment"),
                    ("ORDER_CANCELLED", "Order Cancelled"),
                    ("OTHER", "Other"),
                ],
                max_length=40,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="salescreditnote",
            name="refund_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CUSTOMER_CREDIT", "Credit to Customer Account"),
                    ("BANK_REFUND", "Bank Refund"),
                    ("CASH_REFUND", "Cash Refund"),
                ],
                default="CUSTOMER_CREDIT",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="salescreditnote",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DRAFT", "Draft"),
                    ("ISSUED", "Issued"),
                    ("PARTIALLY_REFUNDED", "Partially Refunded"),
                    ("REFUNDED", "Refunded"),
                    ("VOID", "Void"),
                ],
                default="DRAFT",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="salescreditnoteitem",
            name="invoice_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credit_note_items",
                to="sales.salesinvoiceitem",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="delivery_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "Pending"),
                    ("PARTIALLY_DELIVERED", "Partially Delivered"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="payment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UNPAID", "Unpaid"),
                    ("PARTIALLY_PAID", "Partially Paid"),
                    ("PAID", "Paid"),
                    ("OVERDUE", "Overdue"),
                    ("VOID", "Void"),
                ],
                default="UNPAID",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="payment_terms",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DUE_ON_RECEIPT", "Due on Receipt"),
                    ("NET_7", "Net 7"),
                    ("NET_15", "Net 15"),
                    ("NET_30", "Net 30"),
                    ("NET_45", "Net 45"),
                    ("NET_60", "Net 60"),
                ],
                default="NET_30",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="sale_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ORDER", "Sales Order"),
                    ("STANDALONE", "Standalone"),
                    ("POS", "POS"),
                ],
                default="STANDALONE",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoiceitem",
            name="sales_order_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_items",
                to="sales.salesorderitem",
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="delivery_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OWN_FLEET", "Own Fleet Delivery"),
                    ("COURIER", "Courier"),
                    ("CUSTOMER_PICKUP", "Customer Pickup"),
                    ("THIRD_PARTY", "Third-Party Transport"),
                ],
                default="OWN_FLEET",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("AWAITING_FULFILLMENT", "Awaiting Fulfillment"),
                    ("PARTIALLY_FULFILLED", "Partially Fulfilled"),
                    ("FULFILLED", "Fulfilled"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="DRAFT",
                max_length=40,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="salespayment",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CASH", "Cash"),
                    ("BANK_TRANSFER", "Bank Transfer"),
                    ("CARD", "Card"),
                    ("CHEQUE", "Cheque"),
                    ("OTHER", "Other"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="salespayment",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DRAFT", "Draft"),
                    ("PAID", "Paid"),
                    ("FAILED", "Failed"),
                    ("REVERSED", "Reversed"),
                ],
                default="PAID",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="salesreturn",
            name="reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DAMAGED", "Damaged"),
                    ("DEFECTIVE", "Defective"),
                    ("WRONG_ITEM", "Wrong Item"),
                    ("CUSTOMER_REQUEST", "Customer Request"),
                    ("OTHER", "Other"),
                ],
                max_length=40,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="salesreturn",
            name="resolution",
            field=models.CharField(
                blank=True,
                choices=[
                    ("REFUND", "Refund"),
                    ("CREDIT_NOTE", "Credit Note"),
                    ("REPLACEMENT", "Replacement"),
                    ("STORE_CREDIT", "Store Credit"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="salesreturn",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING_APPROVAL", "Pending Approval"),
                    ("APPROVED", "Approved"),
                    ("COMPLETED", "Completed"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="DRAFT",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="salesreturnitem",
            name="condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SELLABLE", "Sellable"),
                    ("DAMAGED", "Damaged"),
                    ("DEFECTIVE", "Defective"),
                    ("SCRAP", "Scrap"),
                ],
                default="SELLABLE",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="pricelistcustomer",
            constraint=models.UniqueConstraint(
                fields=("price_list", "customer"), name="unique_price_list_customer"
            ),
        ),
    ]
