# Generated by Django 5.2.16 on 2026-07-24 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_alter_possale_options_alter_possaleitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salespayment",
            name="cleared_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salespayment",
            name="reversed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salespayment",
            name="reversed_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesreport",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesreport",
            name="generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesreport",
            name="last_run_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesreturnitem",
            name="sales_order_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="return_items",
                to="sales.salesorderitem",
            ),
        ),
        migrations.AlterField(
            model_name="pricelist",
            name="applies_to",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ALL_CUSTOMERS", "All Customers"),
                    ("CUSTOMER_CATEGORY", "Customer Category"),
                    ("SELECTED_ACCOUNTS", "Selected Accounts"),
                ],
                default="ALL_CUSTOMERS",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pricelist",
            name="discount_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PERCENTAGE", "Percentage Off"),
                    ("FIXED", "Fixed Amount Off"),
                    ("CUSTOM_PRICE", "Custom Item Prices"),
                ],
                default="PERCENTAGE",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="salespayment",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING", "Pending Clearance"),
                    ("PAID", "Paid / Cleared"),
                    ("FAILED", "Failed"),
                    ("REVERSED", "Reversed"),
                ],
                default="PAID",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="salesreturn",
            name="reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DAMAGED", "Damaged / Defective"),
                    ("DEFECTIVE", "Defective"),
                    ("WRONG_ITEM", "Wrong Item Shipped"),
                    ("CUSTOMER_REQUEST", "Customer Changed Mind"),
                    ("QUALITY_ISSUE", "Quality Issue"),
                    ("OTHER", "Other"),
                ],
                max_length=40,
                null=True,
            ),
        ),
    ]
