# Generated by Django 5.2.16 on 2026-07-30 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
        ("sales", "0006_deliverynote_deliverynoteitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverynote",
            name="actual_delivery_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="dispatch_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="driver_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="expected_delivery_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_notes",
                to="sales.salesinvoice",
            ),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="received_by",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="signature_stamp",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="vehicle",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="deliverynoteitem",
            name="serial_imei",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="salesreturn",
            name="approver_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="salesreturn",
            name="disposition",
            field=models.CharField(
                choices=[
                    ("RESTOCK", "Restock"),
                    ("SCRAP", "Scrap"),
                    ("RETURN_TO_SUPPLIER", "Return to Supplier"),
                ],
                default="RESTOCK",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="salesreturn",
            name="refund_method",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="salesreturn",
            name="restock_branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="restocked_sales_returns",
                to="branches.branch",
            ),
        ),
        migrations.AddField(
            model_name="salesreturnitem",
            name="inspected_by_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="salesreturnitem",
            name="serial_imei",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="deliverynote",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("IN_TRANSIT", "In Transit"),
                    ("DELIVERED", "Delivered"),
                    ("PARTIALLY_DELIVERED", "Partially Delivered"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                    ("DRAFT", "Draft"),
                    ("READY", "Ready for Delivery"),
                    ("DISPATCHED", "Dispatched"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
