# Generated by Django 5.2.16 on 2026-07-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0007_deliverynote_actual_delivery_datetime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricelist",
            name="auto_apply",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pricelist",
            name="currency",
            field=models.CharField(default="AED", max_length=3),
        ),
        migrations.AddField(
            model_name="pricelist",
            name="price_list_type",
            field=models.CharField(
                choices=[
                    ("CUSTOMER_TIER", "Customer-Tier"),
                    ("BRANCH_SPECIFIC", "Branch-Specific"),
                    ("PROMOTIONAL", "Promotional"),
                ],
                default="CUSTOMER_TIER",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="pricelist",
            name="stackable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pricelist",
            name="usage_limit_per_customer",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pricelistitem",
            name="discount_percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="pricelistitem",
            name="minimum_quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="pricelist",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DRAFT", "Draft"),
                    ("SCHEDULED", "Scheduled"),
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("EXPIRED", "Expired"),
                ],
                default="DRAFT",
                max_length=20,
                null=True,
            ),
        ),
    ]
