# Generated by Django 5.2.16 on 2026-07-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0008_pricelist_auto_apply_pricelist_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverynote",
            name="supporting_reference",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="tax_inclusive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="tax_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="tax_treatment",
            field=models.CharField(
                choices=[
                    ("STANDARD_VAT", "Standard VAT"),
                    ("ZERO_RATED", "Zero Rated"),
                    ("EXEMPT", "Exempt"),
                    ("NON_TAXABLE", "Non Taxable"),
                ],
                default="STANDARD_VAT",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="possale",
            name="supporting_reference",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="possale",
            name="tax_inclusive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="possale",
            name="tax_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="possale",
            name="tax_treatment",
            field=models.CharField(
                choices=[
                    ("STANDARD_VAT", "Standard VAT"),
                    ("ZERO_RATED", "Zero Rated"),
                    ("EXEMPT", "Exempt"),
                    ("NON_TAXABLE", "Non Taxable"),
                ],
                default="STANDARD_VAT",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="possaleitem",
            name="stock_classification",
            field=models.CharField(
                choices=[("REGULAR", "Regular"), ("RESTRICTED", "Restricted")],
                default="REGULAR",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="possaleitem",
            name="tax_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="possaleitem",
            name="tax_rate",
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
        migrations.AddField(
            model_name="possaleitem",
            name="tax_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="possaleitem",
            name="tax_treatment",
            field=models.CharField(
                choices=[
                    ("STANDARD_VAT", "Standard VAT"),
                    ("ZERO_RATED", "Zero Rated"),
                    ("EXEMPT", "Exempt"),
                    ("NON_TAXABLE", "Non Taxable"),
                ],
                default="STANDARD_VAT",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="possaleitem",
            name="taxable_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="pricelist",
            name="supporting_reference",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="pricelist",
            name="tax_inclusive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pricelist",
            name="tax_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="pricelist",
            name="tax_treatment",
            field=models.CharField(
                choices=[
                    ("STANDARD_VAT", "Standard VAT"),
                    ("ZERO_RATED", "Zero Rated"),
                    ("EXEMPT", "Exempt"),
                    ("NON_TAXABLE", "Non Taxable"),
                ],
                default="STANDARD_VAT",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="supporting_reference",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="quotation",
            name="tax_inclusive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quotation",
            name="tax_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="quotation",
            name="tax_treatment",
            field=models.CharField(
                choices=[
                    ("STANDARD_VAT", "Standard VAT"),
                    ("ZERO_RATED", "Zero Rated"),
                    ("EXEMPT", "Exempt"),
                    ("NON_TAXABLE", "Non Taxable"),
                ],
                default="STANDARD_VAT",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="stock_classification",
            field=models.CharField(
                choices=[("REGULAR", "Regular"), ("RESTRICTED", "Restricted")],
                default="REGULAR",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="tax_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="tax_rate",
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="tax_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="tax_treatment",
            field=models.CharField(
                choices=[
                    ("STANDARD_VAT", "Standard VAT"),
                    ("ZERO_RATED", "Zero Rated"),
                    ("EXEMPT", "Exempt"),
                    ("NON_TAXABLE", "Non Taxable"),
                ],
                default="STANDARD_VAT",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="taxable_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="salescreditnote",
            name="supporting_reference",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="salescreditnote",
            name="tax_inclusive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="salescreditnote",
            name="tax_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="salescreditnote",
            name="tax_treatment",
            field=models.CharField(
                choices=[
                    ("STANDARD_VAT", "Standard VAT"),
                    ("ZERO_RATED", "Zero Rated"),
                    ("EXEMPT", "Exempt"),
                    ("NON_TAXABLE", "Non Taxable"),
                ],
                default="STANDARD_VAT",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="salescreditnoteitem",
            name="stock_classification",
            field=models.CharField(
                choices=[("REGULAR", "Regular"), ("RESTRICTED", "Restricted")],
                default="REGULAR",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="salescreditnoteitem",
            name="tax_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="salescreditnoteitem",
            name="tax_rate",
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
        migrations.AddField(
            model_name="salescreditnoteitem",
            name="tax_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="salescreditnoteitem",
            name="tax_treatment",
            field=models.CharField(
                choices=[
                    ("STANDARD_VAT", "Standard VAT"),
                    ("ZERO_RATED", "Zero Rated"),
                    ("EXEMPT", "Exempt"),
                    ("NON_TAXABLE", "Non Taxable"),
                ],
                default="STANDARD_VAT",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="salescreditnoteitem",
            name="taxable_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="supporting_reference",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="tax_inclusive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="tax_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="tax_treatment",
            field=models.CharField(
                choices=[
                    ("STANDARD_VAT", "Standard VAT"),
                    ("ZERO_RATED", "Zero Rated"),
                    ("EXEMPT", "Exempt"),
                    ("NON_TAXABLE", "Non Taxable"),
                ],
                default="STANDARD_VAT",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="salesinvoiceitem",
            name="stock_classification",
            field=models.CharField(
                choices=[("REGULAR", "Regular"), ("RESTRICTED", "Restricted")],
                default="REGULAR",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="salesinvoiceitem",
            name="tax_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="salesinvoiceitem",
            name="tax_rate",
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
        migrations.AddField(
            model_name="salesinvoiceitem",
            name="tax_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="salesinvoiceitem",
            name="tax_treatment",
            field=models.CharField(
                choices=[
                    ("STANDARD_VAT", "Standard VAT"),
                    ("ZERO_RATED", "Zero Rated"),
                    ("EXEMPT", "Exempt"),
                    ("NON_TAXABLE", "Non Taxable"),
                ],
                default="STANDARD_VAT",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="salesinvoiceitem",
            name="taxable_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="supporting_reference",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="tax_inclusive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="tax_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="tax_treatment",
            field=models.CharField(
                choices=[
                    ("STANDARD_VAT", "Standard VAT"),
                    ("ZERO_RATED", "Zero Rated"),
                    ("EXEMPT", "Exempt"),
                    ("NON_TAXABLE", "Non Taxable"),
                ],
                default="STANDARD_VAT",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="salesorderitem",
            name="stock_classification",
            field=models.CharField(
                choices=[("REGULAR", "Regular"), ("RESTRICTED", "Restricted")],
                default="REGULAR",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="salesorderitem",
            name="tax_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="salesorderitem",
            name="tax_rate",
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
        migrations.AddField(
            model_name="salesorderitem",
            name="tax_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="salesorderitem",
            name="tax_treatment",
            field=models.CharField(
                choices=[
                    ("STANDARD_VAT", "Standard VAT"),
                    ("ZERO_RATED", "Zero Rated"),
                    ("EXEMPT", "Exempt"),
                    ("NON_TAXABLE", "Non Taxable"),
                ],
                default="STANDARD_VAT",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="salesorderitem",
            name="taxable_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="salespayment",
            name="supporting_reference",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="salespayment",
            name="tax_inclusive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="salespayment",
            name="tax_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="salespayment",
            name="tax_treatment",
            field=models.CharField(
                choices=[
                    ("STANDARD_VAT", "Standard VAT"),
                    ("ZERO_RATED", "Zero Rated"),
                    ("EXEMPT", "Exempt"),
                    ("NON_TAXABLE", "Non Taxable"),
                ],
                default="STANDARD_VAT",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="salesreport",
            name="supporting_reference",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="salesreport",
            name="tax_inclusive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="salesreport",
            name="tax_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="salesreport",
            name="tax_treatment",
            field=models.CharField(
                choices=[
                    ("STANDARD_VAT", "Standard VAT"),
                    ("ZERO_RATED", "Zero Rated"),
                    ("EXEMPT", "Exempt"),
                    ("NON_TAXABLE", "Non Taxable"),
                ],
                default="STANDARD_VAT",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="salesreturn",
            name="supporting_reference",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="salesreturn",
            name="tax_inclusive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="salesreturn",
            name="tax_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="salesreturn",
            name="tax_treatment",
            field=models.CharField(
                choices=[
                    ("STANDARD_VAT", "Standard VAT"),
                    ("ZERO_RATED", "Zero Rated"),
                    ("EXEMPT", "Exempt"),
                    ("NON_TAXABLE", "Non Taxable"),
                ],
                default="STANDARD_VAT",
                max_length=30,
            ),
        ),
    ]
