# Generated by Django 5.2.16 on 2026-08-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0009_deliverynote_supporting_reference_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverynote",
            name="tax_treatment",
            field=models.CharField(
                choices=[
                    ("STANDARD_VAT", "Standard VAT"),
                    ("ZERO_RATED", "Zero Rated"),
                    ("EXEMPT", "Exempt"),
                    ("OUT_OF_SCOPE", "Out of Scope"),
                    ("REVERSE_CHARGE", "Reverse Charge"),
                ],
                default="STANDARD_VAT",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="possale",
            name="tax_treatment",
            field=models.CharField(
                choices=[
                    ("STANDARD_VAT", "Standard VAT"),
                    ("ZERO_RATED", "Zero Rated"),
                    ("EXEMPT", "Exempt"),
                    ("OUT_OF_SCOPE", "Out of Scope"),
                    ("REVERSE_CHARGE", "Reverse Charge"),
                ],
                default="STANDARD_VAT",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="possaleitem",
            name="tax_treatment",
            field=models.CharField(
                choices=[
                    ("STANDARD_VAT", "Standard VAT"),
                    ("ZERO_RATED", "Zero Rated"),
                    ("EXEMPT", "Exempt"),
                    ("OUT_OF_SCOPE", "Out of Scope"),
                    ("REVERSE_CHARGE", "Reverse Charge"),
                ],
                default="STANDARD_VAT",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="pricelist",
            name="tax_treatment",
            field=models.CharField(
                choices=[
                    ("STANDARD_VAT", "Standard VAT"),
                    ("ZERO_RATED", "Zero Rated"),
                    ("EXEMPT", "Exempt"),
                    ("OUT_OF_SCOPE", "Out of Scope"),
                    ("REVERSE_CHARGE", "Reverse Charge"),
                ],
                default="STANDARD_VAT",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="tax_treatment",
            field=models.CharField(
                choices=[
                    ("STANDARD_VAT", "Standard VAT"),
                    ("ZERO_RATED", "Zero Rated"),
                    ("EXEMPT", "Exempt"),
                    ("OUT_OF_SCOPE", "Out of Scope"),
                    ("REVERSE_CHARGE", "Reverse Charge"),
                ],
                default="STANDARD_VAT",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="quotationitem",
            name="tax_treatment",
            field=models.CharField(
                choices=[
                    ("STANDARD_VAT", "Standard VAT"),
                    ("ZERO_RATED", "Zero Rated"),
                    ("EXEMPT", "Exempt"),
                    ("OUT_OF_SCOPE", "Out of Scope"),
                    ("REVERSE_CHARGE", "Reverse Charge"),
                ],
                default="STANDARD_VAT",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="salescreditnote",
            name="tax_treatment",
            field=models.CharField(
                choices=[
                    ("STANDARD_VAT", "Standard VAT"),
                    ("ZERO_RATED", "Zero Rated"),
                    ("EXEMPT", "Exempt"),
                    ("OUT_OF_SCOPE", "Out of Scope"),
                    ("REVERSE_CHARGE", "Reverse Charge"),
                ],
                default="STANDARD_VAT",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="salescreditnoteitem",
            name="tax_treatment",
            field=models.CharField(
                choices=[
                    ("STANDARD_VAT", "Standard VAT"),
                    ("ZERO_RATED", "Zero Rated"),
                    ("EXEMPT", "Exempt"),
                    ("OUT_OF_SCOPE", "Out of Scope"),
                    ("REVERSE_CHARGE", "Reverse Charge"),
                ],
                default="STANDARD_VAT",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="tax_treatment",
            field=models.CharField(
                choices=[
                    ("STANDARD_VAT", "Standard VAT"),
                    ("ZERO_RATED", "Zero Rated"),
                    ("EXEMPT", "Exempt"),
                    ("OUT_OF_SCOPE", "Out of Scope"),
                    ("REVERSE_CHARGE", "Reverse Charge"),
                ],
                default="STANDARD_VAT",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoiceitem",
            name="tax_treatment",
            field=models.CharField(
                choices=[
                    ("STANDARD_VAT", "Standard VAT"),
                    ("ZERO_RATED", "Zero Rated"),
                    ("EXEMPT", "Exempt"),
                    ("OUT_OF_SCOPE", "Out of Scope"),
                    ("REVERSE_CHARGE", "Reverse Charge"),
                ],
                default="STANDARD_VAT",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="tax_treatment",
            field=models.CharField(
                choices=[
                    ("STANDARD_VAT", "Standard VAT"),
                    ("ZERO_RATED", "Zero Rated"),
                    ("EXEMPT", "Exempt"),
                    ("OUT_OF_SCOPE", "Out of Scope"),
                    ("REVERSE_CHARGE", "Reverse Charge"),
                ],
                default="STANDARD_VAT",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="salesorderitem",
            name="tax_treatment",
            field=models.CharField(
                choices=[
                    ("STANDARD_VAT", "Standard VAT"),
                    ("ZERO_RATED", "Zero Rated"),
                    ("EXEMPT", "Exempt"),
                    ("OUT_OF_SCOPE", "Out of Scope"),
                    ("REVERSE_CHARGE", "Reverse Charge"),
                ],
                default="STANDARD_VAT",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="salespayment",
            name="tax_treatment",
            field=models.CharField(
                choices=[
                    ("STANDARD_VAT", "Standard VAT"),
                    ("ZERO_RATED", "Zero Rated"),
                    ("EXEMPT", "Exempt"),
                    ("OUT_OF_SCOPE", "Out of Scope"),
                    ("REVERSE_CHARGE", "Reverse Charge"),
                ],
                default="STANDARD_VAT",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="salesreport",
            name="tax_treatment",
            field=models.CharField(
                choices=[
                    ("STANDARD_VAT", "Standard VAT"),
                    ("ZERO_RATED", "Zero Rated"),
                    ("EXEMPT", "Exempt"),
                    ("OUT_OF_SCOPE", "Out of Scope"),
                    ("REVERSE_CHARGE", "Reverse Charge"),
                ],
                default="STANDARD_VAT",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="salesreturn",
            name="tax_treatment",
            field=models.CharField(
                choices=[
                    ("STANDARD_VAT", "Standard VAT"),
                    ("ZERO_RATED", "Zero Rated"),
                    ("EXEMPT", "Exempt"),
                    ("OUT_OF_SCOPE", "Out of Scope"),
                    ("REVERSE_CHARGE", "Reverse Charge"),
                ],
                default="STANDARD_VAT",
                max_length=30,
            ),
        ),
    ]
