# Generated by Django 5.2.17 on 2026-08-08 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0010_alter_deliverynote_tax_treatment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="possaleitem",
            name="stock_classification",
        ),
        migrations.RemoveField(
            model_name="quotationitem",
            name="stock_classification",
        ),
        migrations.RemoveField(
            model_name="salescreditnoteitem",
            name="stock_classification",
        ),
        migrations.RemoveField(
            model_name="salesinvoiceitem",
            name="stock_classification",
        ),
        migrations.RemoveField(
            model_name="salesorderitem",
            name="stock_classification",
        ),
    ]
