# Generated by Django 5.2.17 on 2026-08-08 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0011_remove_possaleitem_stock_classification_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salescreditnoteitem",
            name="credit_note",
        ),
        migrations.RemoveField(
            model_name="salescreditnoteitem",
            name="invoice_item",
        ),
        migrations.RemoveField(
            model_name="salescreditnoteitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="salescreditnoteitem",
            name="variant",
        ),
        migrations.DeleteModel(
            name="SalesCreditNote",
        ),
        migrations.DeleteModel(
            name="SalesCreditNoteItem",
        ),
    ]
