# Generated by Django 5.2.17 on 2026-08-22 04:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
        ("customers", "0003_customer_branch_alter_customer_customer_code_and_more"),
        ("finance", "0011_budgetline_budgetrevision_fixedassetattachment_and_more"),
        ("sales", "0012_remove_salescreditnoteitem_credit_note_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="salesinvoice",
            name="historical_reference",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Original invoice number or reference from the previous system.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="is_historical",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Historical invoices affect accounting only and must not change stock, delivery, or Sales Order fulfilment.",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="delivery_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "Pending"),
                    ("PARTIALLY_DELIVERED", "Partially Delivered"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                    ("NOT_APPLICABLE", "Not Applicable"),
                ],
                default="PENDING",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="sale_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ORDER", "Sales Order"),
                    ("STANDALONE", "Standalone"),
                    ("POS", "POS"),
                    ("HISTORICAL", "Previous / Historical Invoice"),
                ],
                default="STANDALONE",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="salesinvoice",
            index=models.Index(
                fields=["is_historical", "invoice_date"], name="sales_inv_hist_date_idx"
            ),
        ),
    ]
