# Generated by Django 5.2.17 on 2026-09-30 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("branch_data", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="masterinventorysynclog",
            new_name="branch_data_source__803206_idx",
            old_name="branch_data_source__15bc88_idx",
        ),
        migrations.RenameIndex(
            model_name="masterinventorysynclog",
            new_name="branch_data_product_1f0b5e_idx",
            old_name="branch_data_product_272fcf_idx",
        ),
        migrations.RenameIndex(
            model_name="masterinventorysynclog",
            new_name="branch_data_source__3c1508_idx",
            old_name="branch_data_source__6bb734_idx",
        ),
    ]
