# Generated by Django 5.2.16 on 2026-07-24 21:59

import apps.hrms.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
        ("hrms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "entitled_days",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=6, null=True
                    ),
                ),
                (
                    "used_days",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=6, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayrollEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "basic_salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "allowances",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "gross_salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "deductions",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "net_salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("PAID", "Paid"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["employee__first_name"],
            },
        ),
        migrations.CreateModel(
            name="PayrollRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "total_gross",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        null=True,
                    ),
                ),
                (
                    "total_deductions",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        null=True,
                    ),
                ),
                (
                    "total_net",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-period", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SalaryRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("JOINING", "Joining"),
                            ("ANNUAL_INCREMENT", "Annual Increment"),
                            ("PROMOTION", "Promotion"),
                            ("CORRECTION", "Salary Correction"),
                            ("OTHER", "Other"),
                        ],
                        max_length=40,
                        null=True,
                    ),
                ),
                ("effective_from", models.DateField(blank=True, null=True)),
                (
                    "basic_salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "allowances",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "approved_by_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-effective_from", "-id"],
            },
        ),
        migrations.RemoveField(
            model_name="payroll",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="payroll",
            name="employee",
        ),
        migrations.RemoveField(
            model_name="payroll",
            name="generated_by",
        ),
        migrations.AlterModelOptions(
            name="attendance",
            options={"ordering": ["-date", "employee__first_name"]},
        ),
        migrations.AlterModelOptions(
            name="department",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="designation",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={"ordering": ["first_name", "last_name", "id"]},
        ),
        migrations.AlterModelOptions(
            name="employeedocument",
            options={"ordering": ["expiry_date", "-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="leaverequest",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="labour_card_expiry_date",
            new_name="driving_license_issue_date",
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="department",
            name="description",
        ),
        migrations.RemoveField(
            model_name="department",
            name="manager",
        ),
        migrations.RemoveField(
            model_name="designation",
            name="description",
        ),
        migrations.RemoveField(
            model_name="designation",
            name="title",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="bank_account_number",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="bank_name",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="emergency_contact_name",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="emergency_contact_number",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="emergency_contact_relationship",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="emirates_id_copy",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="housing_allowance",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="iban_number",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="labour_card_number",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="other_allowance",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="passport_copy",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="personal_email",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="personal_mobile",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="reporting_manager",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="status",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="transport_allowance",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="visa_copy",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="work_email",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="wps_number",
        ),
        migrations.RemoveField(
            model_name="employeedocument",
            name="attachment",
        ),
        migrations.RemoveField(
            model_name="employeedocument",
            name="reminder_days_before",
        ),
        migrations.RemoveField(
            model_name="employeedocument",
            name="status",
        ),
        migrations.RemoveField(
            model_name="leaverequest",
            name="approval_remarks",
        ),
        migrations.RemoveField(
            model_name="leaverequest",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="leaverequest",
            name="attachment",
        ),
        migrations.RemoveField(
            model_name="leaverequest",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="leaverequest",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="leaverequest",
            name="total_days",
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_in",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_out",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PRESENT", "Present"),
                    ("ABSENT", "Absent"),
                    ("LATE", "Late"),
                    ("LEAVE", "Leave"),
                    ("HALF_DAY", "Half Day"),
                    ("HOLIDAY", "Holiday"),
                    ("WEEK_OFF", "Week Off"),
                ],
                default="PRESENT",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="code",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="designation",
            name="designation_name",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="designation",
            name="name",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="allowances",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="insurance_issue_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="insurance_provider",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="is_active",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="labor_contract_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="labor_contract_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="labor_contract_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="labor_contract_status",
            field=models.CharField(
                blank=True, default="ACTIVE", max_length=30, null=True
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="labor_contract_type",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="phone",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="visa_sponsor",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="visa_status",
            field=models.CharField(
                blank=True, default="VALID", max_length=30, null=True
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="visa_type",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="employeedocument",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.hrms.models.employee_document_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png", "doc", "docx"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="employeedocument",
            name="title",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="employeedocument",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_employee_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="action_remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="actioned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="actioned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actioned_leave_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leave_requests",
                to="branches.branch",
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="days",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=1, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="from_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="supporting_document",
            field=models.FileField(blank=True, null=True, upload_to="hrms/leaves/"),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="to_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="code",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="requires_document",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendance_records",
                to="branches.branch",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="hrms.employee",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="overtime_hours",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="remarks",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="working_hours",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="is_active",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="designation",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="designations",
                to="hrms.department",
            ),
        ),
        migrations.AlterField(
            model_name="designation",
            name="is_active",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="basic_salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="branches.branch",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="hrms.department",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="designation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="hrms.designation",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="driving_license_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emirates_id_number",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employee_code",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ACTIVE", "Active"),
                    ("ON_LEAVE", "On Leave"),
                    ("PROBATION", "Probation"),
                    ("RESIGNED", "Resigned"),
                    ("TERMINATED", "Terminated"),
                    ("INACTIVE", "Inactive"),
                ],
                default="ACTIVE",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FULL_TIME", "Full Time"),
                    ("PART_TIME", "Part Time"),
                    ("CONTRACT", "Contract"),
                    ("INTERN", "Intern"),
                ],
                default="FULL_TIME",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="insurance_policy_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="joining_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="nationality",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="passport_number",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="hrms/employees/profile/"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="visa_number",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="employeedocument",
            name="document_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="employeedocument",
            name="document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PASSPORT", "Passport"),
                    ("EMIRATES_ID", "Emirates ID"),
                    ("VISA", "Visa"),
                    ("LABOR_CONTRACT", "Labor Contract"),
                    ("EDUCATION", "Education Certificate"),
                    ("MEDICAL", "Medical"),
                    ("INSURANCE", "Insurance"),
                    ("OTHER", "Other"),
                ],
                max_length=40,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="employeedocument",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="hrms.employee",
            ),
        ),
        migrations.AlterField(
            model_name="employeedocument",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_requests",
                to="hrms.employee",
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="leave_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leave_requests",
                to="hrms.leavetype",
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="leavetype",
            name="annual_limit",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="leavetype",
            name="is_active",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="leavetype",
            name="is_paid",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="leavetype",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                fields=("employee", "date"), name="unique_employee_attendance_date"
            ),
        ),
        migrations.AddField(
            model_name="leavebalance",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_balances",
                to="hrms.employee",
            ),
        ),
        migrations.AddField(
            model_name="leavebalance",
            name="leave_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="balances",
                to="hrms.leavetype",
            ),
        ),
        migrations.AddField(
            model_name="payrollentry",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payroll_entries",
                to="branches.branch",
            ),
        ),
        migrations.AddField(
            model_name="payrollentry",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payroll_entries",
                to="hrms.employee",
            ),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payroll_runs",
                to="branches.branch",
            ),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="generated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_payroll_runs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payrollentry",
            name="payroll_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="hrms.payrollrun",
            ),
        ),
        migrations.AddField(
            model_name="salaryrevision",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_salary_revisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="salaryrevision",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salary_revisions",
                to="hrms.employee",
            ),
        ),
        migrations.DeleteModel(
            name="Payroll",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="attendance_date",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="attendance_status",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="marked_by",
        ),
        migrations.AddConstraint(
            model_name="leavebalance",
            constraint=models.UniqueConstraint(
                fields=("employee", "leave_type", "year"),
                name="unique_employee_leave_balance",
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollentry",
            constraint=models.UniqueConstraint(
                fields=("employee", "period"), name="unique_employee_payroll_period"
            ),
        ),
    ]
