# Generated by Django 5.2.16 on 2026-07-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0002_leavebalance_payrollentry_payrollrun_salaryrevision_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salaryrevision",
            name="deductions",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="salaryrevision",
            name="effective_to",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salaryrevision",
            name="payment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salaryrevision",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="salaryrevision",
            name="payroll_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("PAID", "Paid"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PAID",
                max_length=20,
                null=True,
            ),
        ),
    ]
