# Generated by Django 5.2.16 on 2026-07-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0003_salaryrevision_deductions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollrun",
            name="from_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="to_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
