# Generated by Django 5.2.16 on 2026-07-28 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0004_payrollrun_from_date_payrollrun_to_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payrollrun",
            name="from_date",
        ),
        migrations.RemoveField(
            model_name="payrollrun",
            name="to_date",
        ),
    ]
