# Generated by Django 5.2.16 on 2026-07-31 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0005_remove_payrollrun_from_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollentry",
            name="payable_days",
            field=models.DecimalField(decimal_places=2, default=30, max_digits=6),
        ),
        migrations.AddField(
            model_name="payrollentry",
            name="salary_calculation_method",
            field=models.CharField(
                choices=[
                    ("FULL", "Full Salary"),
                    ("PRORATED", "Prorated by Payable Days"),
                ],
                default="FULL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="payrollentry",
            name="total_period_days",
            field=models.DecimalField(decimal_places=2, default=30, max_digits=6),
        ),
        migrations.AddField(
            model_name="payrollentry",
            name="unpaid_leave_days",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
