# Generated by Django 5.2.16 on 2026-08-01 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
        ("hrms", "0006_payrollentry_payable_days_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payrollentry",
            options={"ordering": ["-payroll_date", "employee__first_name"]},
        ),
        migrations.AlterModelOptions(
            name="payrollrun",
            options={"ordering": ["-payroll_date", "-period", "-id"]},
        ),
        migrations.RemoveConstraint(
            model_name="payrollentry",
            name="unique_employee_payroll_period",
        ),
        migrations.AddField(
            model_name="payrollentry",
            name="advance_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="payrollentry",
            name="advance_deduction",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="payrollentry",
            name="balance_payable",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="payrollentry",
            name="paid_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paid_payroll_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payrollentry",
            name="payroll_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payrollentry",
            name="salary_type",
            field=models.CharField(
                choices=[("REGULAR", "Regular Salary"), ("ADVANCE", "Advance Salary")],
                default="REGULAR",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="paid_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paid_payroll_runs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="payroll_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="salary_type",
            field=models.CharField(
                choices=[("REGULAR", "Regular Salary"), ("ADVANCE", "Advance Salary")],
                default="REGULAR",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="total_advance_deduction",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name="payrollentry",
            name="period",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name="payrollentry",
            name="salary_calculation_method",
            field=models.CharField(
                choices=[
                    ("FULL", "Full Salary"),
                    ("PRORATED", "Prorated Salary"),
                    ("ADVANCE", "Advance Salary"),
                ],
                default="FULL",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payrollrun",
            name="period",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddConstraint(
            model_name="payrollentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("salary_type", "REGULAR")),
                fields=("employee", "period"),
                name="unique_regular_employee_payroll_period",
            ),
        ),
    ]
