# Generated by Django 5.2.16 on 2026-08-02 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
        ("hrms", "0007_alter_payrollentry_options_alter_payrollrun_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryAdvance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period",
                    models.CharField(
                        help_text="Payroll period in YYYY-MM format.", max_length=7
                    ),
                ),
                ("advance_date", models.DateField()),
                (
                    "salary_at_time",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "remaining_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("paid_by", models.CharField(blank=True, default="", max_length=255)),
                (
                    "reference_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("CANCELLED", "Cancelled"),
                            ("DEDUCTED", "Deducted"),
                        ],
                        default="PAID",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["-advance_date", "-id"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="payrollentry",
            name="unique_regular_employee_payroll_period",
        ),
        migrations.AlterField(
            model_name="payrollentry",
            name="allowances",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="payrollentry",
            name="basic_salary",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="payrollentry",
            name="deductions",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="payrollentry",
            name="gross_salary",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="payrollentry",
            name="net_salary",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="payrollentry",
            name="paid_by",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="payrollentry",
            name="salary_calculation_method",
            field=models.CharField(
                choices=[("FULL", "Full Salary"), ("PRORATED", "Prorated Salary")],
                default="FULL",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payrollentry",
            name="salary_type",
            field=models.CharField(
                choices=[
                    ("REGULAR", "Regular Salary"),
                    ("ADVANCE", "Legacy Advance Salary"),
                ],
                default="REGULAR",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payrollentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("PAID", "Paid"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payrollrun",
            name="paid_by",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="payrollrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payrollrun",
            name="total_deductions",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name="payrollrun",
            name="total_gross",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name="payrollrun",
            name="total_net",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddConstraint(
            model_name="payrollentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("salary_type", "REGULAR")),
                fields=("employee", "period"),
                name="unique_regular_payroll_employee_period",
            ),
        ),
        migrations.AddField(
            model_name="salaryadvance",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="salary_advances",
                to="branches.branch",
            ),
        ),
        migrations.AddField(
            model_name="salaryadvance",
            name="deducted_payroll_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deducted_salary_advances",
                to="hrms.payrollentry",
            ),
        ),
        migrations.AddField(
            model_name="salaryadvance",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="salary_advances",
                to="hrms.employee",
            ),
        ),
        migrations.AddIndex(
            model_name="salaryadvance",
            index=models.Index(
                fields=["employee", "period", "status"],
                name="hrms_adv_emp_period_status",
            ),
        ),
    ]
