# Generated by Django 5.2.17 on 2026-08-12 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0008_salaryadvance_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference_number", models.CharField(max_length=50, unique=True)),
                ("certificate_date", models.DateField()),
                ("employee_name", models.CharField(max_length=220)),
                (
                    "employee_code",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "identity_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "designation_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("joining_date", models.DateField(blank=True, null=True)),
                (
                    "basic_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "housing_allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "transport_other_allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("authorized_signatory", models.CharField(max_length=150)),
                ("signatory_designation", models.CharField(max_length=150)),
                (
                    "purpose",
                    models.CharField(
                        blank=True, default="Official purposes", max_length=255
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="salary_certificates",
                        to="hrms.employee",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_salary_certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-certificate_date", "-id"],
            },
        ),
    ]
