# Generated by Django 5.2.17 on 2026-08-16 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0009_salarycertificate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "letter_type",
                    models.CharField(
                        choices=[
                            ("WARNING", "Warning Letter"),
                            ("EXPERIENCE", "Experience Letter"),
                        ],
                        max_length=30,
                    ),
                ),
                ("reference_number", models.CharField(max_length=50, unique=True)),
                ("letter_date", models.DateField()),
                ("employee_name", models.CharField(max_length=220)),
                (
                    "employee_code",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "designation_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "department_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("joining_date", models.DateField(blank=True, null=True)),
                ("subject", models.CharField(blank=True, default="", max_length=255)),
                ("reason", models.TextField(blank=True, default="")),
                ("details", models.TextField(blank=True, default="")),
                ("last_working_date", models.DateField(blank=True, null=True)),
                ("experience_summary", models.TextField(blank=True, default="")),
                (
                    "conduct_note",
                    models.TextField(
                        blank=True,
                        default="During the employment period, the employee carried out assigned duties and responsibilities.",
                    ),
                ),
                ("authorized_signatory", models.CharField(max_length=150)),
                ("signatory_designation", models.CharField(max_length=150)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_letters",
                        to="hrms.employee",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_employee_letters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-letter_date", "-id"],
            },
        ),
    ]
