# Generated by Django 5.2.17 on 2026-08-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0010_employeeletter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeletter",
            name="authorized_signatory",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="employeeletter",
            name="signatory_designation",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
