# Generated by Django 5.2.17 on 2026-08-19 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
        ("hrms", "0011_alter_employeeletter_authorized_signatory_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollentry",
            name="loan_deduction",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name="EmployeeLoan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("loan_date", models.DateField()),
                (
                    "start_period",
                    models.CharField(
                        help_text="First deduction month in YYYY-MM format.",
                        max_length=7,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "monthly_installment",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "remaining_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "reference_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_loans",
                        to="branches.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_employee_loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_loans",
                        to="hrms.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-loan_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeLoanRepayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period", models.CharField(max_length=7)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loan_repayments",
                        to="hrms.employee",
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="repayments",
                        to="hrms.employeeloan",
                    ),
                ),
                (
                    "payroll_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loan_repayments",
                        to="hrms.payrollentry",
                    ),
                ),
            ],
            options={
                "ordering": ["-period", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("loan", "payroll_entry"),
                        name="unique_loan_payroll_repayment",
                    )
                ],
            },
        ),
    ]
