# Generated by Django 5.2.17 on 2026-09-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0012_payrollentry_loan_deduction_employeeloan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeletter",
            name="letter_type",
            field=models.CharField(
                choices=[
                    ("WARNING", "Warning Letter"),
                    ("EXPERIENCE", "Experience Letter"),
                    ("EMPLOYMENT", "Employment Certificate"),
                    ("NOC", "NOC Letter"),
                    ("SALARY_TRANSFER", "Salary Transfer Letter"),
                    ("PROMOTION", "Promotion Letter"),
                    ("TERMINATION", "Termination Letter"),
                    ("CUSTOM", "Custom Letter"),
                ],
                max_length=30,
            ),
        ),
    ]
