# Generated by Django 5.2.16 on 2026-07-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["customer_name", "id"]},
        ),
        migrations.AddField(
            model_name="customer",
            name="billing_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RETAIL", "Retail"),
                    ("WHOLESALE", "Wholesale"),
                    ("CORPORATE", "Corporate"),
                    ("LEAD", "Lead"),
                ],
                default="RETAIL",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="payment_terms",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DUE_ON_RECEIPT", "Due on Receipt"),
                    ("NET_15", "Net 15"),
                    ("NET_30", "Net 30"),
                    ("NET_60", "Net 60"),
                ],
                default="NET_30",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="trade_license",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="trn",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="city",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="contact_person",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="country",
            field=models.CharField(blank=True, default="UAE", max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="credit_limit",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="customer_type",
            field=models.CharField(
                blank=True,
                choices=[("BUSINESS", "Business"), ("INDIVIDUAL", "Individual")],
                default="BUSINESS",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="emirate",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="opening_balance",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="payment_terms_days",
            field=models.PositiveIntegerField(blank=True, default=30, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="trn_number",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="whatsapp_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
