# Generated by Django 5.2.17 on 2026-08-08 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
        ("customers", "0002_alter_customer_options_customer_billing_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customers",
                to="branches.branch",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="customer_code",
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                fields=("branch", "customer_code"),
                name="unique_customer_code_per_branch",
            ),
        ),
    ]
