# Generated by Django 5.2.17 on 2026-08-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_role_options_role_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="permissions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Operation-level permissions assigned directly to this user.",
            ),
        ),
    ]
