# Generated by Django 5.2.16 on 2026-07-25 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_stockadjustment_actual_quantity_counted_and_more"),
        ("transfers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktransferitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transfer_items",
                to="inventory.productvariant",
            ),
        ),
    ]
