# Generated by Django 5.2.16 on 2026-08-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transfers", "0002_stocktransferitem_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktransfer",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="capitalized_vat_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="courier_cost_excluding_vat",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="courier_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="courier_vat_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="courier_vat_percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="courier_vat_treatment",
            field=models.CharField(default="OUT_OF_SCOPE", max_length=30),
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="destination_stock_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="dispatched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="reconciliation_status",
            field=models.CharField(default="PENDING", max_length=30),
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="source_stock_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="tax_scope",
            field=models.CharField(default="OUT_OF_SCOPE", max_length=30),
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="total_transfer_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="transfer_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="value_difference",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="stocktransferitem",
            name="destination_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="stocktransferitem",
            name="line_transfer_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="stocktransferitem",
            name="source_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="stocktransferitem",
            name="stock_classification",
            field=models.CharField(default="REGULAR", max_length=20),
        ),
        migrations.AddField(
            model_name="stocktransferitem",
            name="transfer_unit_cost",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="stocktransferitem",
            name="value_difference",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
