# Generated by Django 5.2.16 on 2026-08-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "transfers",
            "0003_stocktransfer_approved_at_stocktransfer_cancelled_at_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stocktransferitem",
            name="stock_classification",
        ),
    ]
