# Generated by Django 5.2.16 on 2026-07-29 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
        ("finance", "0002_alter_bankaccount_current_balance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chartofaccount",
            name="lock_from_posting",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chartofaccount",
            name="normal_balance",
            field=models.CharField(
                choices=[("DEBIT", "Debit"), ("CREDIT", "Credit")],
                default="DEBIT",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="chartofaccount",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="chartofaccount",
            name="sub_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CURRENT_ASSET", "Current Asset"),
                    ("BANK", "Bank"),
                    ("CASH", "Cash"),
                    ("ACCOUNTS_RECEIVABLE", "Accounts Receivable"),
                    ("INVENTORY", "Inventory"),
                    ("PREPAID_EXPENSE", "Prepaid Expense"),
                    ("FIXED_ASSET", "Fixed Asset"),
                    ("ACCUMULATED_DEPRECIATION", "Accumulated Depreciation"),
                    ("OTHER_ASSET", "Other Asset"),
                    ("CURRENT_LIABILITY", "Current Liability"),
                    ("ACCOUNTS_PAYABLE", "Accounts Payable"),
                    ("VAT_PAYABLE", "VAT Payable"),
                    ("ACCRUED_EXPENSE", "Accrued Expense"),
                    ("PAYROLL_PAYABLE", "Payroll Payable"),
                    ("LONG_TERM_LIABILITY", "Long-term Liability"),
                    ("OTHER_LIABILITY", "Other Liability"),
                    ("OWNER_EQUITY", "Owner's Equity"),
                    ("RETAINED_EARNINGS", "Retained Earnings"),
                    ("CURRENT_YEAR_EARNINGS", "Current Year Earnings"),
                    ("SALES_REVENUE", "Sales Revenue"),
                    ("SERVICE_REVENUE", "Service Revenue"),
                    ("OTHER_INCOME", "Other Income"),
                    ("COST_OF_GOODS_SOLD", "Cost of Goods Sold"),
                    ("PAYROLL_EXPENSE", "Payroll Expense"),
                    ("RENT_EXPENSE", "Rent Expense"),
                    ("DEPRECIATION_EXPENSE", "Depreciation Expense"),
                    ("UTILITY_EXPENSE", "Utility Expense"),
                    ("BANK_CHARGE", "Bank Charges"),
                    ("OTHER_EXPENSE", "Other Expense"),
                ],
                max_length=40,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chartofaccount",
            name="tax_treatment",
            field=models.CharField(
                choices=[
                    ("NOT_APPLICABLE", "Not Applicable"),
                    ("VAT_STANDARD", "VAT Applicable — Standard 5%"),
                    ("VAT_ZERO", "VAT Zero-rated"),
                    ("VAT_EXEMPT", "VAT Exempt"),
                    ("VAT_INPUT", "VAT Input / Recoverable"),
                    ("VAT_OUTPUT", "VAT Output / Payable"),
                ],
                default="NOT_APPLICABLE",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="chartofaccount",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("ASSET", "Asset"),
                    ("LIABILITY", "Liability"),
                    ("EQUITY", "Equity"),
                    ("INCOME", "Income / Revenue"),
                    ("EXPENSE", "Expense"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="chartofaccount",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave blank to make this account available to all branches.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="branches.branch",
            ),
        ),
        migrations.AlterField(
            model_name="chartofaccount",
            name="code",
            field=models.CharField(max_length=5),
        ),
        migrations.AddConstraint(
            model_name="chartofaccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("branch__isnull", True)),
                fields=("code",),
                name="uniq_finance_global_account_code",
            ),
        ),
    ]
