# Generated by Django 5.2.16 on 2026-07-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_assetdepreciationrun_assetdepreciationline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fixedasset",
            name="allow_branch_transfer",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="capitalization_threshold",
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=16),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="custodian",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="depreciation_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="depreciation_start_rule",
            field=models.CharField(
                choices=[
                    ("PURCHASE_DATE", "Date of Purchase"),
                    ("NEXT_MONTH", "First Day of Next Month"),
                    ("CUSTOM_DATE", "Custom Date"),
                ],
                default="PURCHASE_DATE",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="production_capacity",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="supplier_invoice_reference",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="tag_retired",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="fixedasset",
            name="depreciation_method",
            field=models.CharField(
                choices=[
                    ("STRAIGHT_LINE", "Straight Line"),
                    ("DECLINING", "Declining Balance"),
                    ("UNITS_OF_PRODUCTION", "Units of Production"),
                ],
                default="STRAIGHT_LINE",
                max_length=30,
            ),
        ),
    ]
