# Generated by Django 5.2.16 on 2026-07-29 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
        ("finance", "0006_fixedasset_allow_branch_transfer_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="budget",
            options={"ordering": ["-fiscal_year", "account__code", "id"]},
        ),
        migrations.AddField(
            model_name="budget",
            name="alert_threshold_percent",
            field=models.PositiveSmallIntegerField(default=90),
        ),
        migrations.AddField(
            model_name="budget",
            name="cost_centre",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="budget",
            name="department_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="budget",
            name="monthly_phasing",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="budget",
            name="notify_option",
            field=models.CharField(
                choices=[
                    ("OWNER", "Budget Owner"),
                    ("FINANCE_MANAGER", "Finance Manager"),
                    ("OWNER_FINANCE_MANAGER", "Budget Owner + Finance Manager"),
                ],
                default="OWNER_FINANCE_MANAGER",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="phasing_method",
            field=models.CharField(
                choices=[
                    ("EVEN", "Even monthly"),
                    ("SEASONAL", "Seasonal weighting"),
                    ("CUSTOM", "Custom monthly amounts"),
                ],
                default="EVEN",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="revision_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="budget",
            name="revision_number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="budget",
            name="rolling_forecast_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="budget",
            name="spend_alert_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="budget",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="budgets",
                to="finance.chartofaccount",
            ),
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.UniqueConstraint(
                fields=(
                    "branch",
                    "fiscal_year",
                    "account",
                    "department_name",
                    "cost_centre",
                    "revision_number",
                ),
                name="uniq_budget_scope_revision",
            ),
        ),
    ]
