# Generated by Django 5.2.17 on 2026-08-11 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "finance",
            "0007_alter_budget_options_budget_alert_threshold_percent_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journalentry",
            options={"ordering": ["-entry_date", "-id"]},
        ),
        migrations.AddField(
            model_name="journalentry",
            name="approval_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="approval_priority",
            field=models.CharField(
                choices=[("NORMAL", "Normal"), ("HIGH", "High"), ("URGENT", "Urgent")],
                default="NORMAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="currency",
            field=models.CharField(default="AED", max_length=3),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="document_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="exchange_rate",
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="recurrence_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="recurrence_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rejected_journals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="reversal_narration",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="reversed_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reversal_entries",
                to="finance.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="source",
            field=models.CharField(
                choices=[("MANUAL", "Manual"), ("SYSTEM", "System-generated")],
                default="MANUAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalline",
            name="cost_center",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="journalline",
            name="project",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="recurrence_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MONTHLY", "Monthly"),
                    ("QUARTERLY", "Quarterly"),
                    ("YEARLY", "Yearly"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING_APPROVAL", "Pending Approval"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("POSTED", "Posted"),
                    ("REVERSED", "Reversed"),
                ],
                default="DRAFT",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="voucher_type",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Manual Journal"),
                    ("ADJUSTMENT", "Adjustment"),
                    ("OPENING_BALANCE", "Opening Balance"),
                    ("ACCRUAL", "Accrual"),
                    ("YEAR_END", "Year End"),
                    ("REVERSAL", "Reversal"),
                ],
                default="MANUAL",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="JournalAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="finance/journals/supporting/")),
                ("original_name", models.CharField(blank=True, max_length=255)),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="finance.journalentry",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journal_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
