# Generated by Django 5.2.17 on 2026-08-11 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0008_alter_journalentry_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="receivableinvoice",
            name="billing_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="receivableinvoice",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="receivableinvoice",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancelled_receivable_invoices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="receivableinvoice",
            name="cost_center",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="receivableinvoice",
            name="currency",
            field=models.CharField(default="AED", max_length=3),
        ),
        migrations.AddField(
            model_name="receivableinvoice",
            name="customer_po_reference",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="receivableinvoice",
            name="delivery_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="receivableinvoice",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="receivableinvoice",
            name="exchange_rate",
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name="receivableinvoice",
            name="internal_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="receivableinvoice",
            name="invoice_narration",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="receivableinvoice",
            name="last_reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="receivableinvoice",
            name="place_of_supply",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="receivableinvoice",
            name="posted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="receivableinvoice",
            name="posted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posted_receivable_invoices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="receivableinvoice",
            name="price_list_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="receivableinvoice",
            name="revenue_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receivable_revenue_invoices",
                to="finance.chartofaccount",
            ),
        ),
        migrations.AddField(
            model_name="receivableinvoice",
            name="salesperson_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="receivableinvoice",
            name="taxable_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="receivableinvoiceline",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="receivableinvoiceline",
            name="discount_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="receivableinvoiceline",
            name="item_service",
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name="receivableinvoiceline",
            name="line_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="receivableinvoiceline",
            name="tax_category",
            field=models.CharField(
                choices=[
                    ("STANDARD", "VAT 5%"),
                    ("ZERO_RATED", "Zero Rated"),
                    ("EXEMPT", "Exempt"),
                    ("NON_VAT", "Non-VAT"),
                ],
                default="STANDARD",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="receivableinvoiceline",
            name="taxable_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name="receivableinvoice",
            name="allow_credit_note_write_off",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="receivableinvoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("OPEN", "Open"),
                    ("SENT", "Sent"),
                    ("PARTIALLY_PAID", "Partially Paid"),
                    ("PAID", "Paid"),
                    ("OVERDUE", "Overdue"),
                    ("CANCELLED", "Cancelled"),
                    ("WRITTEN_OFF", "Written Off"),
                ],
                default="DRAFT",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="receivableinvoiceline",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="receivablereceipt",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receipts",
                to="finance.receivableinvoice",
            ),
        ),
        migrations.CreateModel(
            name="ReceivableInvoiceAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="finance/receivables/supporting/")),
                ("original_name", models.CharField(blank=True, max_length=255)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="finance.receivableinvoice",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receivable_invoice_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
