# Generated by Django 5.2.17 on 2026-08-11 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0009_receivableinvoice_billing_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payablebill",
            name="approval_threshold",
        ),
        migrations.RemoveField(
            model_name="payablebill",
            name="route_for_approval",
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="account_type",
            field=models.CharField(
                choices=[("BANK", "Bank"), ("CASH", "Cash")],
                default="BANK",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="chart_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bank_cash_accounts",
                to="finance.chartofaccount",
            ),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="currency",
            field=models.CharField(default="AED", max_length=3),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="last_reconciled_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="statement_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="bankfundtransfer",
            name="status",
            field=models.CharField(default="POSTED", max_length=20),
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="reconciled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="reconciled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reconciled_bank_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payablebill",
            name="approval_priority",
            field=models.CharField(
                choices=[("NORMAL", "Normal"), ("HIGH", "High"), ("URGENT", "Urgent")],
                default="NORMAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="payablebill",
            name="approval_workflow",
            field=models.CharField(
                blank=True, default="AP_ACCOUNTANT_FINANCE_MANAGER", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="payablebill",
            name="bill_narration",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="payablebill",
            name="buyer_requester",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="payablebill",
            name="cost_center",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="payablebill",
            name="currency",
            field=models.CharField(default="AED", max_length=3),
        ),
        migrations.AddField(
            model_name="payablebill",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="payablebill",
            name="exchange_rate",
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name="payablebill",
            name="expense_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payable_expense_bills",
                to="finance.chartofaccount",
            ),
        ),
        migrations.AddField(
            model_name="payablebill",
            name="internal_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="payablebill",
            name="match_method",
            field=models.CharField(
                choices=[
                    ("THREE_WAY", "Three-way match"),
                    ("TWO_WAY", "Two-way match"),
                    ("NO_PO", "No PO"),
                ],
                default="NO_PO",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="payablebill",
            name="match_status",
            field=models.CharField(
                choices=[
                    ("NOT_MATCHED", "Not Matched"),
                    ("MATCHED", "Matched"),
                    ("VARIANCE", "Variance"),
                ],
                default="NOT_MATCHED",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="payablebill",
            name="matched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payablebill",
            name="matched_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matched_payable_bills",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payablebill",
            name="payment_method",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="payablebill",
            name="posted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payablebill",
            name="posted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posted_payable_bills",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payablebill",
            name="project",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="payablebill",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payablebill",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rejected_payable_bills",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payablebill",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="payablebill",
            name="taxable_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="payablebillline",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="payablebillline",
            name="discount_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="payablebillline",
            name="item_expense",
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name="payablebillline",
            name="line_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="payablebillline",
            name="tax_category",
            field=models.CharField(
                choices=[
                    ("STANDARD", "VAT 5%"),
                    ("ZERO_RATED", "Zero Rated"),
                    ("EXEMPT", "Exempt"),
                    ("NON_VAT", "Non-VAT"),
                ],
                default="STANDARD",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="payablebillline",
            name="taxable_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="account_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="bank_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="payablebill",
            name="payment_terms",
            field=models.CharField(
                choices=[
                    ("DUE_ON_RECEIPT", "Due on Receipt"),
                    ("NET_15", "Net 15"),
                    ("NET_30", "Net 30"),
                    ("NET_60", "Net 60"),
                ],
                default="NET_30",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="payablebill",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING_APPROVAL", "Pending Approval"),
                    ("APPROVED", "Approved"),
                    ("POSTED", "Posted"),
                    ("REJECTED", "Rejected"),
                    ("PARTIALLY_PAID", "Partially Paid"),
                    ("PAID", "Paid"),
                    ("OVERDUE", "Overdue"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="DRAFT",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="payablebillline",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="PayableBillAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="finance/payables/supporting/")),
                ("original_name", models.CharField(blank=True, max_length=255)),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="finance.payablebill",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payable_bill_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
