# Generated by Django 5.2.17 on 2026-08-11 15:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
        ("finance", "0010_remove_payablebill_approval_threshold_and_more"),
        (
            "suppliers",
            "0004_supplier_branch_alter_supplier_payment_terms_days_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("department", models.CharField(blank=True, max_length=150)),
                ("cost_center", models.CharField(blank=True, max_length=150)),
                (
                    "jan",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "feb",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "mar",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "apr",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "may",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "jun",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "jul",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "aug",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "sep",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "oct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "nov",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "dec",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BudgetRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision_number", models.CharField(max_length=50, unique=True)),
                (
                    "revision_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("revision_type", models.CharField(max_length=40)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=16)),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FixedAssetAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="finance/fixed-assets/")),
                ("original_name", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FixedAssetDepreciation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period", models.CharField(max_length=7)),
                ("opening_nbv", models.DecimalField(decimal_places=2, max_digits=16)),
                (
                    "depreciation_amount",
                    models.DecimalField(decimal_places=2, max_digits=16),
                ),
                ("closing_nbv", models.DecimalField(decimal_places=2, max_digits=16)),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("journal_reference", models.CharField(blank=True, max_length=80)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FixedAssetDisposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("disposal_number", models.CharField(max_length=50, unique=True)),
                ("disposal_date", models.DateField()),
                ("disposal_method", models.CharField(max_length=40)),
                (
                    "original_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "accumulated_depreciation",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "net_book_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "proceeds",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "gain_loss",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("status", models.CharField(default="PENDING_APPROVAL", max_length=30)),
                ("journal_reference", models.CharField(blank=True, max_length=80)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FixedAssetMaintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("job_number", models.CharField(max_length=50, unique=True)),
                ("maintenance_type", models.CharField(max_length=80)),
                ("scheduled_date", models.DateField()),
                ("vendor_technician", models.CharField(blank=True, max_length=180)),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "actual_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("downtime", models.CharField(blank=True, max_length=80)),
                ("status", models.CharField(default="SCHEDULED", max_length=30)),
                ("next_service_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FixedAssetTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("transfer_number", models.CharField(max_length=50, unique=True)),
                (
                    "transfer_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("from_location", models.CharField(blank=True, max_length=180)),
                ("to_location", models.CharField(max_length=180)),
                ("from_custodian", models.CharField(blank=True, max_length=180)),
                ("to_custodian", models.CharField(max_length=180)),
                ("reason", models.TextField(blank=True)),
                ("status", models.CharField(default="PENDING_APPROVAL", max_length=30)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VatReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company_name",
                    models.CharField(default="Ghaza Computer TR LLC", max_length=180),
                ),
                ("trn", models.CharField(blank=True, max_length=50)),
                (
                    "return_type",
                    models.CharField(
                        choices=[
                            ("VAT201", "VAT 201 — Regular Return"),
                            ("AMENDED", "Amended Return"),
                        ],
                        default="VAT201",
                        max_length=20,
                    ),
                ),
                (
                    "return_frequency",
                    models.CharField(
                        choices=[("MONTHLY", "Monthly"), ("QUARTERLY", "Quarterly")],
                        default="QUARTERLY",
                        max_length=20,
                    ),
                ),
                ("period_from", models.DateField()),
                ("period_to", models.DateField()),
                ("filing_due_date", models.DateField(blank=True, null=True)),
                (
                    "output_vat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "input_vat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "prior_period_credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "net_vat_payable",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("total_transactions", models.PositiveIntegerField(default=0)),
                ("valid_transactions", models.PositiveIntegerField(default=0)),
                ("warnings_count", models.PositiveIntegerField(default=0)),
                ("errors_count", models.PositiveIntegerField(default=0)),
                ("reviewer_notes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("filing_reference", models.CharField(blank=True, max_length=120)),
                ("submission_date", models.DateField(blank=True, null=True)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("NOT_PAID", "Not Paid"),
                            ("SCHEDULED", "Scheduled"),
                            ("PAID", "Paid"),
                        ],
                        default="NOT_PAID",
                        max_length=20,
                    ),
                ),
                ("payment_reference", models.CharField(blank=True, max_length=120)),
                ("payment_account", models.CharField(blank=True, max_length=180)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("VALIDATED", "Validated"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("FILED", "Filed"),
                            ("PAID", "Paid"),
                        ],
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
            ],
            options={
                "ordering": ["-period_to", "-id"],
            },
        ),
        migrations.CreateModel(
            name="VatReturnBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("box_number", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=255)),
                (
                    "taxable_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "vat_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "adjustment_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "final_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("status", models.CharField(default="VALID", max_length=20)),
            ],
            options={
                "ordering": ["box_number", "id"],
            },
        ),
        migrations.CreateModel(
            name="VatSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company_name",
                    models.CharField(default="Ghaza Computer TR LLC", max_length=180),
                ),
                ("company_trn", models.CharField(blank=True, max_length=50)),
                (
                    "registration_country",
                    models.CharField(default="United Arab Emirates", max_length=100),
                ),
                (
                    "return_frequency",
                    models.CharField(
                        choices=[("MONTHLY", "Monthly"), ("QUARTERLY", "Quarterly")],
                        default="QUARTERLY",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "VAT Setting",
                "verbose_name_plural": "VAT Settings",
            },
        ),
        migrations.AlterModelOptions(
            name="budget",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="budget",
            name="uniq_budget_scope_revision",
        ),
        migrations.RenameField(
            model_name="budget",
            old_name="rolling_forecast_enabled",
            new_name="allow_budget_transfers",
        ),
        migrations.RenameField(
            model_name="budget",
            old_name="revision_note",
            new_name="approval_notes",
        ),
        migrations.RenameField(
            model_name="budget",
            old_name="spend_alert_enabled",
            new_name="block_over_budget",
        ),
        migrations.RenameField(
            model_name="budget",
            old_name="department_name",
            new_name="department_scope",
        ),
        migrations.RenameField(
            model_name="budget",
            old_name="period_from",
            new_name="end_date",
        ),
        migrations.RenameField(
            model_name="budget",
            old_name="period_to",
            new_name="start_date",
        ),
        migrations.RenameField(
            model_name="budget",
            old_name="actual_amount",
            new_name="variance_tolerance",
        ),
        migrations.RenameField(
            model_name="budget",
            old_name="revision_number",
            new_name="version",
        ),
        migrations.RenameField(
            model_name="fixedasset",
            old_name="allow_branch_transfer",
            new_name="allow_impairment",
        ),
        migrations.RenameField(
            model_name="fixedasset",
            old_name="name",
            new_name="asset_name",
        ),
        migrations.RenameField(
            model_name="fixedasset",
            old_name="asset_code",
            new_name="asset_tag",
        ),
        migrations.RenameField(
            model_name="fixedasset",
            old_name="notes",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="budget",
            name="account",
        ),
        migrations.RemoveField(
            model_name="budget",
            name="alert_threshold_percent",
        ),
        migrations.RemoveField(
            model_name="budget",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="budget",
            name="budget_amount",
        ),
        migrations.RemoveField(
            model_name="budget",
            name="cost_centre",
        ),
        migrations.RemoveField(
            model_name="budget",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="budget",
            name="monthly_phasing",
        ),
        migrations.RemoveField(
            model_name="budget",
            name="name",
        ),
        migrations.RemoveField(
            model_name="budget",
            name="notify_option",
        ),
        migrations.RemoveField(
            model_name="budget",
            name="phasing_method",
        ),
        migrations.RemoveField(
            model_name="budget",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="fixedasset",
            name="capitalization_threshold",
        ),
        migrations.RemoveField(
            model_name="fixedasset",
            name="depreciation_start_rule",
        ),
        migrations.RemoveField(
            model_name="fixedasset",
            name="production_capacity",
        ),
        migrations.RemoveField(
            model_name="fixedasset",
            name="purchase_cost",
        ),
        migrations.RemoveField(
            model_name="fixedasset",
            name="supplier_invoice_reference",
        ),
        migrations.RemoveField(
            model_name="fixedasset",
            name="tag_retired",
        ),
        migrations.AddField(
            model_name="budget",
            name="activated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="budget",
            name="activated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activated_budgets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="approval_priority",
            field=models.CharField(default="NORMAL", max_length=20),
        ),
        migrations.AddField(
            model_name="budget",
            name="approval_workflow",
            field=models.CharField(default="DEPT_FINANCE_MD", max_length=80),
        ),
        migrations.AddField(
            model_name="budget",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="budget",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_budgets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="block_threshold_percent",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
        ),
        migrations.AddField(
            model_name="budget",
            name="branch_scope",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="finance_budgets",
                to="branches.branch",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="budget_name",
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name="budget",
            name="budget_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="budget",
            name="budget_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_budgets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="budget_type",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="budget",
            name="commitment_basis",
            field=models.CharField(default="ACTUAL_PO_REQUISITION", max_length=50),
        ),
        migrations.AddField(
            model_name="budget",
            name="company_name",
            field=models.CharField(default="Ghaza Computer TR LLC", max_length=180),
        ),
        migrations.AddField(
            model_name="budget",
            name="control_level",
            field=models.CharField(default="ACCOUNT_DEPARTMENT_BRANCH", max_length=50),
        ),
        migrations.AddField(
            model_name="budget",
            name="cost_inflation_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name="budget",
            name="currency",
            field=models.CharField(default="AED", max_length=3),
        ),
        migrations.AddField(
            model_name="budget",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="budget",
            name="enable_budget_control",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="budget",
            name="exchange_rate_assumption",
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name="budget",
            name="headcount_growth_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name="budget",
            name="include_commitments",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="budget",
            name="primary_approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="budget_primary_approvals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="budget",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rejected_budgets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="budget",
            name="revenue_growth_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name="budget",
            name="revision_policy",
            field=models.CharField(default="APPROVAL_REQUIRED", max_length=40),
        ),
        migrations.AddField(
            model_name="budget",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="budget",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_budgets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="warning_threshold_percent",
            field=models.DecimalField(decimal_places=2, default=80, max_digits=6),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="accumulated_depreciation_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fixed_asset_accumulated_assets",
                to="finance.chartofaccount",
            ),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="acquisition_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="acquisition_type",
            field=models.CharField(default="PURCHASED", max_length=30),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="additional_capitalized_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_fixed_assets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fixed_asset_approvals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="asset_class",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="assigned_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="barcode",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="capitalization_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="capitalized_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="capitalized_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="capitalized_fixed_assets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="condition",
            field=models.CharField(default="NEW", max_length=30),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="cost_center",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="currency",
            field=models.CharField(default="AED", max_length=3),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="department",
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="depreciate_asset",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="depreciation_book",
            field=models.CharField(default="CORPORATE", max_length=30),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="depreciation_expense_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fixed_asset_expense_assets",
                to="finance.chartofaccount",
            ),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="depreciation_frequency",
            field=models.CharField(default="MONTHLY", max_length=20),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="disposal_gain_loss_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fixed_asset_disposal_assets",
                to="finance.chartofaccount",
            ),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="exchange_rate",
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="financial_dimension",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="fixed_asset_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fixed_asset_cost_assets",
                to="finance.chartofaccount",
            ),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="goods_receipt",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="insurance_expiry",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="insurance_policy_number",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="location",
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="maintenance_frequency",
            field=models.CharField(default="NOT_REQUIRED", max_length=30),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="maintenance_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="manufacturer",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="model",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="next_service_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="physical_verification_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="placed_in_service_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="project",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="proration_convention",
            field=models.CharField(default="DAILY", max_length=30),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="purchase_order",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rejected_fixed_assets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="serial_number",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="service_vendor",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="suppliers.supplier",
            ),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="supplier_invoice",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="tax_depreciation_method",
            field=models.CharField(default="SAME_AS_BOOK", max_length=30),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="warranty_expiry",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="warranty_reference",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="warranty_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="budget",
            name="fiscal_year",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="budget",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING_APPROVAL", "Pending Approval"),
                    ("APPROVED", "Approved"),
                    ("ACTIVE", "Active"),
                    ("REJECTED", "Rejected"),
                    ("ARCHIVED", "Archived"),
                ],
                default="DRAFT",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="fixedasset",
            name="category",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="fixedasset",
            name="custodian",
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name="fixedasset",
            name="depreciation_method",
            field=models.CharField(
                choices=[
                    ("STRAIGHT_LINE", "Straight Line"),
                    ("DECLINING_BALANCE", "Declining Balance"),
                    ("UNITS_OF_PRODUCTION", "Units of Production"),
                    ("NO_DEPRECIATION", "No Depreciation"),
                ],
                default="STRAIGHT_LINE",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="fixedasset",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING_APPROVAL", "Pending Approval"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("ACTIVE", "Active"),
                    ("UNDER_MAINTENANCE", "Under Maintenance"),
                    ("FULLY_DEPRECIATED", "Fully Depreciated"),
                    ("DISPOSED", "Disposed"),
                ],
                default="DRAFT",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="fixedasset",
            name="useful_life_months",
            field=models.PositiveIntegerField(default=36),
        ),
        migrations.AddField(
            model_name="budgetline",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="finance.chartofaccount"
            ),
        ),
        migrations.AddField(
            model_name="budgetline",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="branches.branch",
            ),
        ),
        migrations.AddField(
            model_name="budgetline",
            name="budget",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="finance.budget",
            ),
        ),
        migrations.AddField(
            model_name="budgetrevision",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_budget_revisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="budgetrevision",
            name="budget",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revisions",
                to="finance.budget",
            ),
        ),
        migrations.AddField(
            model_name="budgetrevision",
            name="from_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="finance.chartofaccount",
            ),
        ),
        migrations.AddField(
            model_name="budgetrevision",
            name="to_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="finance.chartofaccount",
            ),
        ),
        migrations.AddField(
            model_name="fixedassetattachment",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="finance.fixedasset",
            ),
        ),
        migrations.AddField(
            model_name="fixedassetattachment",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fixedassetdepreciation",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="depreciation_rows",
                to="finance.fixedasset",
            ),
        ),
        migrations.AddField(
            model_name="fixedassetdepreciation",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="branches.branch",
            ),
        ),
        migrations.AddField(
            model_name="fixedassetdepreciation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_%(class)s_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fixedassetdepreciation",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(class)s_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fixedassetdisposal",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="disposals",
                to="finance.fixedasset",
            ),
        ),
        migrations.AddField(
            model_name="fixedassetdisposal",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="branches.branch",
            ),
        ),
        migrations.AddField(
            model_name="fixedassetdisposal",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_%(class)s_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fixedassetdisposal",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(class)s_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fixedassetmaintenance",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="maintenance_jobs",
                to="finance.fixedasset",
            ),
        ),
        migrations.AddField(
            model_name="fixedassetmaintenance",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="branches.branch",
            ),
        ),
        migrations.AddField(
            model_name="fixedassetmaintenance",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_%(class)s_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fixedassetmaintenance",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(class)s_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fixedassettransfer",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fixedassettransfer",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transfers",
                to="finance.fixedasset",
            ),
        ),
        migrations.AddField(
            model_name="fixedassettransfer",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_records",
                to="branches.branch",
            ),
        ),
        migrations.AddField(
            model_name="fixedassettransfer",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_%(class)s_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fixedassettransfer",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(class)s_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vatreturn",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_vat_returns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vatreturn",
            name="assigned_approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_vat_returns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vatreturn",
            name="branch_scope",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vat_returns",
                to="branches.branch",
            ),
        ),
        migrations.AddField(
            model_name="vatreturn",
            name="filed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="filed_vat_returns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vatreturn",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_vat_returns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vatreturnbox",
            name="vat_return",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boxes",
                to="finance.vatreturn",
            ),
        ),
        migrations.AddField(
            model_name="vatsettings",
            name="input_vat_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vat_settings_input_accounts",
                to="finance.chartofaccount",
            ),
        ),
        migrations.AddField(
            model_name="vatsettings",
            name="output_vat_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vat_settings_output_accounts",
                to="finance.chartofaccount",
            ),
        ),
        migrations.AddField(
            model_name="vatsettings",
            name="vat_payable_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vat_settings_payable_accounts",
                to="finance.chartofaccount",
            ),
        ),
        migrations.AddConstraint(
            model_name="vatreturn",
            constraint=models.UniqueConstraint(
                fields=("branch_scope", "return_type", "period_from", "period_to"),
                name="uniq_vat_return_scope_period",
            ),
        ),
    ]
