# Generated by Django 5.2.16 on 2026-07-23 08:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supplier",
            options={"ordering": ["supplier_name"]},
        ),
        migrations.AddField(
            model_name="supplier",
            name="account_holder_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="supplier",
            name="auto_block_credit_limit",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="bank_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="supplier",
            name="billing_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="currency",
            field=models.CharField(
                choices=[
                    ("AED", "AED"),
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                    ("INR", "INR"),
                ],
                default="AED",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="designation",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="supplier",
            name="iban",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="supplier",
            name="send_payment_reminders",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="supplier",
            name="supplier_category",
            field=models.CharField(
                choices=[
                    ("LAPTOPS", "Laptops"),
                    ("ELECTRONICS", "Electronics & Components"),
                    ("SPARE_PARTS", "Spare Parts"),
                    ("SERVICES", "Services"),
                    ("OTHER", "Other"),
                ],
                default="ELECTRONICS",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="swift_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="supplier",
            name="trade_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="payment_terms_days",
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(
                fields=["supplier_name"], name="suppliers_s_supplie_60545a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(
                fields=["supplier_code"], name="suppliers_s_supplie_97d6e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(
                fields=["is_active"], name="suppliers_s_is_acti_a75d30_idx"
            ),
        ),
    ]
