# Generated by Django 5.2.16 on 2026-08-06 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
        ("suppliers", "0003_supplierdocument"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="suppliers",
                to="branches.branch",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="payment_terms_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="supplier_code",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(
                fields=["branch", "supplier_code"],
                name="suppliers_s_branch__b88eb0_idx",
            ),
        ),
    ]
