# Generated by Django 5.2.16 on 2026-07-18 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_productvariant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="minimum_selling_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="purchase_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="retail_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="wholesale_price",
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="minimum_selling_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="purchase_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="retail_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="wholesale_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
