# Generated by Django 5.2.16 on 2026-07-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_remove_product_minimum_selling_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="initial_available_qty",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Opening quantity available when this variant is first created.",
            ),
        ),
    ]
