# Generated by Django 5.2.16 on 2026-07-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_productvariant_initial_available_qty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariant",
            name="initial_available_qty",
        ),
        migrations.AddField(
            model_name="productvariant",
            name="available_qty",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Current available quantity for this product variant.",
            ),
        ),
    ]
