# Generated by Django 5.2.16 on 2026-07-20 10:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_remove_productvariant_initial_available_qty_and_more"),
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="condition",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("USED", "Used"),
                    ("REFURBISHED", "Refurbished"),
                ],
                default="NEW",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[
                    ("PCS", "Pcs"),
                    ("SET", "Set"),
                    ("BOX", "Box"),
                    ("PACK", "Pack"),
                    ("PAIR", "Pair"),
                ],
                default="PCS",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="vat_inclusive",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="vat_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=5,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="suppliers.supplier",
            ),
        ),
    ]
