# Generated by Django 5.2.16 on 2026-07-20 18:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
        (
            "inventory",
            "0006_product_condition_product_unit_product_vat_inclusive_and_more",
        ),
        ("suppliers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rack_code", models.CharField(max_length=50)),
                ("rack_name", models.CharField(blank=True, max_length=120)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["branch", "rack_code"],
            },
        ),
        migrations.AlterModelOptions(
            name="productvariant",
            options={"ordering": ["product", "id"]},
        ),
        migrations.RemoveIndex(
            model_name="productvariant",
            name="inventory_p_sku_3e98d7_idx",
        ),
        migrations.RemoveIndex(
            model_name="productvariant",
            name="inventory_p_barcode_af1594_idx",
        ),
        migrations.RenameField(
            model_name="productvariant",
            old_name="is_default",
            new_name="is_base",
        ),
        migrations.RemoveField(
            model_name="product",
            name="rack_location",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="barcode",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="sku",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="variant_name",
        ),
        migrations.AddField(
            model_name="product",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="branches.branch",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="has_variants",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="available_qty",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="purchase_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_base", True)),
                fields=("product",),
                name="one_base_variant_per_product",
            ),
        ),
        migrations.AddField(
            model_name="rack",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="racks",
                to="branches.branch",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="rack",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="inventory.rack",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["branch", "is_active"], name="inventory_p_branch__4c740b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rack",
            index=models.Index(
                fields=["branch", "is_active"], name="inventory_r_branch__5cff8b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rack",
            index=models.Index(
                fields=["rack_code"], name="inventory_r_rack_co_0ef9dd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="rack",
            constraint=models.UniqueConstraint(
                fields=("branch", "rack_code"), name="unique_rack_code_per_branch"
            ),
        ),
    ]
