# Generated by Django 5.2.16 on 2026-07-21 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_rack_alter_productvariant_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brand",
            name="description",
        ),
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
        migrations.RemoveField(
            model_name="rack",
            name="description",
        ),
    ]
