# Generated by Django 5.2.16 on 2026-07-21 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
        (
            "inventory",
            "0008_remove_brand_description_remove_category_description_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productstock",
            options={"ordering": ["product__product_name", "branch__branch_code"]},
        ),
        migrations.AlterModelOptions(
            name="stockadjustment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="stockmovement",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="productstock",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="productstock",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branch_stocks",
                to="inventory.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="stockadjustment",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_adjustments",
                to="inventory.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_movements",
                to="inventory.productvariant",
            ),
        ),
        migrations.AlterField(
            model_name="stockadjustment",
            name="adjustment_type",
            field=models.CharField(
                choices=[("ADD", "Increase"), ("DEDUCT", "Decrease")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="stockadjustment",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_adjustments",
                to="inventory.product",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_movements",
                to="branches.branch",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("OPENING", "Opening Stock"),
                    ("PURCHASE", "Purchase"),
                    ("SALE", "Sale"),
                    ("CUSTOMER_RETURN", "Customer Return"),
                    ("SUPPLIER_RETURN", "Supplier Return"),
                    ("TRANSFER_OUT", "Transfer Out"),
                    ("TRANSFER_IN", "Transfer In"),
                    ("ADJUSTMENT", "Adjustment"),
                    ("DAMAGED", "Damaged Stock"),
                    ("INTERNAL", "Internal Use"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_movements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_movements",
                to="inventory.product",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="quantity",
            field=models.IntegerField(
                help_text="Signed quantity. Positive increases stock and negative decreases stock."
            ),
        ),
        migrations.AddIndex(
            model_name="productstock",
            index=models.Index(
                fields=["product", "branch"], name="inventory_p_product_43f286_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productstock",
            index=models.Index(
                fields=["variant", "branch"], name="inventory_p_variant_f2e9e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productstock",
            index=models.Index(
                fields=["branch", "current_stock"],
                name="inventory_p_branch__1aadb0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockadjustment",
            index=models.Index(
                fields=["branch", "created_at"], name="inventory_s_branch__ae692d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockadjustment",
            index=models.Index(
                fields=["product", "created_at"], name="inventory_s_product_bfb4c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockadjustment",
            index=models.Index(
                fields=["status", "created_at"], name="inventory_s_status_9d7ee3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["branch", "created_at"], name="inventory_s_branch__377a2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["product", "created_at"], name="inventory_s_product_5919a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["variant", "created_at"], name="inventory_s_variant_183f66_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["movement_type", "created_at"],
                name="inventory_s_movemen_ed5291_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="productstock",
            constraint=models.UniqueConstraint(
                condition=models.Q(("variant__isnull", True)),
                fields=("product", "branch"),
                name="unique_base_product_stock_per_branch",
            ),
        ),
        migrations.AddConstraint(
            model_name="productstock",
            constraint=models.UniqueConstraint(
                condition=models.Q(("variant__isnull", False)),
                fields=("variant", "branch"),
                name="unique_variant_stock_per_branch",
            ),
        ),
    ]
