# Generated by Django 5.2.16 on 2026-07-22 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_alter_productstock_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockadjustment",
            name="actual_quantity_counted",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="stockadjustment",
            name="current_quantity",
            field=models.IntegerField(default=0),
        ),
    ]
