# Generated by Django 5.2.16 on 2026-07-31 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
        ("inventory", "0010_stockadjustment_actual_quantity_counted_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="productstock",
            name="regular_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productstock",
            name="reserved_regular_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productstock",
            name="reserved_restricted_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productstock",
            name="restricted_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productstock",
            name="warehouse",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="stock_classification",
            field=models.CharField(
                choices=[("REGULAR", "Regular"), ("RESTRICTED", "Restricted")],
                default="REGULAR",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="warehouse",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("OPENING", "Opening Stock"),
                    ("PURCHASE", "Purchase"),
                    ("PURCHASE_REGULAR", "Purchase - Regular"),
                    ("PURCHASE_RESTRICTED", "Purchase - Restricted"),
                    ("SALE", "Sale"),
                    ("SALE_REGULAR", "Sale - Regular"),
                    ("SALE_RESTRICTED", "Sale - Restricted"),
                    ("RECLASSIFICATION_OUT", "Reclassification Out"),
                    ("RECLASSIFICATION_IN", "Reclassification In"),
                    ("CUSTOMER_RETURN", "Customer Return"),
                    ("SUPPLIER_RETURN", "Supplier Return"),
                    ("TRANSFER_OUT", "Transfer Out"),
                    ("TRANSFER_IN", "Transfer In"),
                    ("ADJUSTMENT", "Adjustment"),
                    ("DAMAGED", "Damaged Stock"),
                    ("INTERNAL", "Internal Use"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="StockReclassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference_number", models.CharField(max_length=50, unique=True)),
                ("warehouse", models.CharField(blank=True, default="", max_length=120)),
                (
                    "source_classification",
                    models.CharField(
                        choices=[("REGULAR", "Regular"), ("RESTRICTED", "Restricted")],
                        max_length=20,
                    ),
                ),
                (
                    "destination_classification",
                    models.CharField(
                        choices=[("REGULAR", "Regular"), ("RESTRICTED", "Restricted")],
                        max_length=20,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("reason", models.TextField()),
                (
                    "supporting_document",
                    models.FileField(
                        blank=True, null=True, upload_to="stock-reclassification/"
                    ),
                ),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_stock_reclassifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_records",
                        to="branches.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_reclassifications",
                        to="inventory.product",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_stock_reclassifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_reclassifications",
                        to="inventory.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("view_restricted_stock", "Can view restricted stock"),
                    ("manage_restricted_stock", "Can manage restricted stock"),
                    (
                        "approve_stock_reclassification",
                        "Can approve stock reclassification",
                    ),
                ],
            },
        ),
    ]
