# Generated by Django 5.2.16 on 2026-08-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
        ("inventory", "0011_productstock_regular_quantity_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productstock",
            options={
                "ordering": [
                    "product__product_name",
                    "branch__branch_code",
                    "warehouse",
                ]
            },
        ),
        migrations.RemoveConstraint(
            model_name="productstock",
            name="unique_base_product_stock_per_branch",
        ),
        migrations.RemoveConstraint(
            model_name="productstock",
            name="unique_variant_stock_per_branch",
        ),
        migrations.RemoveIndex(
            model_name="productstock",
            name="inventory_p_product_43f286_idx",
        ),
        migrations.RemoveIndex(
            model_name="productstock",
            name="inventory_p_variant_f2e9e2_idx",
        ),
        migrations.RemoveIndex(
            model_name="productstock",
            name="inventory_p_branch__1aadb0_idx",
        ),
        migrations.AlterField(
            model_name="productstock",
            name="damaged_stock",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="productstock",
            name="regular_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="productstock",
            name="reserved_regular_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="productstock",
            name="reserved_restricted_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="productstock",
            name="restricted_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="productstock",
            index=models.Index(
                fields=["product", "branch", "warehouse"],
                name="inventory_p_product_3f2d67_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productstock",
            index=models.Index(
                fields=["variant", "branch", "warehouse"],
                name="inventory_p_variant_511ddc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productstock",
            index=models.Index(
                fields=["branch", "regular_quantity"],
                name="inventory_p_branch__69f67c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productstock",
            index=models.Index(
                fields=["branch", "restricted_quantity"],
                name="inventory_p_branch__cccffb_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="productstock",
            constraint=models.UniqueConstraint(
                condition=models.Q(("variant__isnull", True)),
                fields=("product", "branch", "warehouse"),
                name="unique_base_stock_per_branch_warehouse",
            ),
        ),
        migrations.AddConstraint(
            model_name="productstock",
            constraint=models.UniqueConstraint(
                condition=models.Q(("variant__isnull", False)),
                fields=("variant", "branch", "warehouse"),
                name="unique_variant_stock_per_branch_warehouse",
            ),
        ),
        migrations.AddConstraint(
            model_name="productstock",
            constraint=models.CheckConstraint(
                condition=models.Q(("regular_quantity__gte", 0)),
                name="product_stock_regular_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="productstock",
            constraint=models.CheckConstraint(
                condition=models.Q(("restricted_quantity__gte", 0)),
                name="product_stock_restricted_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="productstock",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reserved_regular_quantity__lte", models.F("regular_quantity"))
                ),
                name="reserved_regular_not_above_regular",
            ),
        ),
        migrations.AddConstraint(
            model_name="productstock",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "reserved_restricted_quantity__lte",
                        models.F("restricted_quantity"),
                    )
                ),
                name="reserved_restricted_not_above_restricted",
            ),
        ),
    ]
