# Generated by Django 5.2.16 on 2026-08-01 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_alter_productstock_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="productstock",
            name="average_unit_cost",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="productstock",
            name="average_unit_cost_excluding_vat",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="productstock",
            name="capitalized_vat_per_unit",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="productstock",
            name="last_purchase_cost",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="productstock",
            name="last_purchase_cost_excluding_vat",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="productstock",
            name="last_tax_treatment",
            field=models.CharField(default="OUT_OF_SCOPE", max_length=30),
        ),
        migrations.AddField(
            model_name="productstock",
            name="last_vat_percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="productstock",
            name="recoverable_vat_per_unit",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="productstock",
            name="valuation_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stockadjustment",
            name="accounting_reference",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="stockadjustment",
            name="adjustment_reason",
            field=models.CharField(default="OTHER", max_length=40),
        ),
        migrations.AddField(
            model_name="stockadjustment",
            name="approval_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="stockadjustment",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stockadjustment",
            name="capitalized_adjustment_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="stockadjustment",
            name="non_recoverable_vat_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="stockadjustment",
            name="quantity_difference",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="stockadjustment",
            name="recoverable_vat_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="stockadjustment",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stockadjustment",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rejected_adjustments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stockadjustment",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="stockadjustment",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stockadjustment",
            name="unit_cost_excluding_vat",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="stockadjustment",
            name="value_after",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="stockadjustment",
            name="value_before",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="stockadjustment",
            name="vat_percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="stockadjustment",
            name="vat_treatment",
            field=models.CharField(default="OUT_OF_SCOPE", max_length=30),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="capitalized_unit_cost",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="gross_value_change",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="is_vat_relevant",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="net_value_change",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="non_recoverable_vat_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="quantity_after",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="quantity_before",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="recoverable_vat_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="running_stock_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="source_document_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="source_document_type",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="tax_invoice_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="tax_invoice_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="unit_cost_excluding_vat",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="valuation_method",
            field=models.CharField(default="WEIGHTED_AVERAGE", max_length=20),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="vat_percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="vat_treatment",
            field=models.CharField(default="OUT_OF_SCOPE", max_length=30),
        ),
    ]
