# Generated by Django 5.2.16 on 2026-08-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_productstock_average_unit_cost_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockadjustment",
            name="adjustment_reason",
        ),
        migrations.AlterField(
            model_name="productstock",
            name="last_vat_percentage",
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
        migrations.AlterField(
            model_name="stockadjustment",
            name="vat_percentage",
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="vat_percentage",
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
    ]
