# Generated by Django 5.2.16 on 2026-08-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_remove_stockadjustment_adjustment_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockadjustment",
            name="adjustment_reason",
            field=models.CharField(default="OTHER", max_length=40),
        ),
        migrations.AddField(
            model_name="stockadjustment",
            name="stock_classification",
            field=models.CharField(
                choices=[("REGULAR", "Regular"), ("RESTRICTED", "Restricted")],
                default="REGULAR",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="productstock",
            name="last_vat_percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="stockadjustment",
            name="vat_percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="vat_percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
