# Generated by Django 5.2.16 on 2026-08-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
        ("inventory", "0015_stockadjustment_adjustment_reason_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockreclassification",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="stockreclassification",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="stockreclassification",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="stockreclassification",
            name="product",
        ),
        migrations.RemoveField(
            model_name="stockreclassification",
            name="requested_by",
        ),
        migrations.RemoveField(
            model_name="stockreclassification",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="stockreclassification",
            name="variant",
        ),
        migrations.RemoveConstraint(
            model_name="productstock",
            name="product_stock_regular_non_negative",
        ),
        migrations.RemoveConstraint(
            model_name="productstock",
            name="product_stock_restricted_non_negative",
        ),
        migrations.RemoveConstraint(
            model_name="productstock",
            name="reserved_regular_not_above_regular",
        ),
        migrations.RemoveConstraint(
            model_name="productstock",
            name="reserved_restricted_not_above_restricted",
        ),
        migrations.RemoveIndex(
            model_name="productstock",
            name="inventory_p_branch__69f67c_idx",
        ),
        migrations.RemoveIndex(
            model_name="productstock",
            name="inventory_p_branch__cccffb_idx",
        ),
        migrations.RemoveField(
            model_name="productstock",
            name="regular_quantity",
        ),
        migrations.RemoveField(
            model_name="productstock",
            name="reserved_regular_quantity",
        ),
        migrations.RemoveField(
            model_name="productstock",
            name="reserved_restricted_quantity",
        ),
        migrations.RemoveField(
            model_name="productstock",
            name="restricted_quantity",
        ),
        migrations.RemoveField(
            model_name="stockadjustment",
            name="stock_classification",
        ),
        migrations.RemoveField(
            model_name="stockmovement",
            name="stock_classification",
        ),
        migrations.AddField(
            model_name="product",
            name="tax_treatment",
            field=models.CharField(
                choices=[
                    ("VAT", "VAT (5%)"),
                    ("ZERO_VAT", "Zero VAT (0%)"),
                    ("NON_VAT", "Non-VAT"),
                ],
                default="VAT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="productstock",
            name="current_stock",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="productstock",
            name="last_tax_treatment",
            field=models.CharField(default="NON_VAT", max_length=20),
        ),
        migrations.AlterField(
            model_name="productstock",
            name="reserved_stock",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("OPENING", "Opening Stock"),
                    ("PURCHASE", "Purchase"),
                    ("SALE", "Sale"),
                    ("CUSTOMER_RETURN", "Customer Return"),
                    ("SUPPLIER_RETURN", "Supplier Return"),
                    ("TRANSFER_OUT", "Transfer Out"),
                    ("TRANSFER_IN", "Transfer In"),
                    ("ADJUSTMENT", "Adjustment"),
                    ("DAMAGED", "Damaged Stock"),
                    ("INTERNAL", "Internal Use"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="productstock",
            index=models.Index(
                fields=["branch", "current_stock"],
                name="inventory_p_branch__1aadb0_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="productstock",
            constraint=models.CheckConstraint(
                condition=models.Q(("current_stock__gte", 0)),
                name="product_stock_current_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="productstock",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved_stock__gte", 0)),
                name="product_stock_reserved_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="productstock",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved_stock__lte", models.F("current_stock"))),
                name="reserved_stock_not_above_current_stock",
            ),
        ),
        migrations.DeleteModel(
            name="StockReclassification",
        ),
    ]
