# Generated by Django 5.2.16 on 2026-08-05 14:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
        ("inventory", "0016_remove_stockreclassification_approved_by_and_more"),
        ("suppliers", "0003_supplierdocument"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(max_length=80),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["branch", "sku"], name="inventory_p_branch__8b8f88_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(("branch__isnull", False)),
                fields=("branch", "sku"),
                name="unique_product_sku_per_branch",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(("branch__isnull", True)),
                fields=("sku",),
                name="unique_unassigned_product_sku",
            ),
        ),
    ]
