# Generated by Django 5.2.16 on 2026-08-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0017_alter_product_sku_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="compatible_models",
            field=models.TextField(blank=True, default="All Models"),
        ),
    ]
