# Generated by Django 5.2.17 on 2026-09-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0018_alter_product_compatible_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="racks",
            field=models.ManyToManyField(
                blank=True,
                help_text="Physical rack locations where this product variant is stored.",
                related_name="product_variants",
                to="inventory.rack",
            ),
        ),
    ]
