# Generated by Django 5.2.17 on 2026-09-30 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recovery", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="recoveryrecord",
            new_name="recovery_re_status_13d0f6_idx",
            old_name="recovery_re_status_74ed0f_idx",
        ),
        migrations.RenameIndex(
            model_name="recoveryrecord",
            new_name="recovery_re_content_a5f648_idx",
            old_name="recovery_re_content_0c3b32_idx",
        ),
    ]
