# Generated by Django 5.2.16 on 2026-07-23 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
        ("inventory", "0010_stockadjustment_actual_quantity_counted_and_more"),
        ("purchases", "0002_alter_goodsreceivednote_options_and_more"),
        ("sales", "0001_initial"),
        ("shipments", "0001_initial"),
        (
            "suppliers",
            "0002_alter_supplier_options_supplier_account_holder_name_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shipment",
            options={"ordering": ["-shipment_date", "-id"]},
        ),
        migrations.AddField(
            model_name="shipment",
            name="courier",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="shipment",
            name="expected_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipments",
                to="purchases.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="received_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_shipments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="received_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipment_method",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipment_type",
            field=models.CharField(
                choices=[("PURCHASE", "Purchase Receipt"), ("SALES", "Sales Delivery")],
                default="PURCHASE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipments",
                to="suppliers.supplier",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="delivery_address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="delivery_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_shipments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="sales.salesinvoice",
            ),
        ),
        migrations.CreateModel(
            name="ShipmentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expected_quantity", models.PositiveIntegerField(default=0)),
                ("received_quantity", models.PositiveIntegerField(default=0)),
                ("accepted_quantity", models.PositiveIntegerField(default=0)),
                ("rejected_quantity", models.PositiveIntegerField(default=0)),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("GOOD", "Good"),
                            ("DAMAGED", "Damaged"),
                            ("PARTIAL", "Partial"),
                        ],
                        default="GOOD",
                        max_length=20,
                    ),
                ),
                ("batch_number", models.CharField(blank=True, max_length=100)),
                ("serial_number", models.CharField(blank=True, max_length=150)),
                ("remarks", models.TextField(blank=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.product",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shipments.shipment",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.productvariant",
                    ),
                ),
            ],
        ),
    ]
