# Generated by Django 5.2.16 on 2026-07-23 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_stockadjustment_actual_quantity_counted_and_more"),
        ("shipments", "0002_alter_shipment_options_shipment_courier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="checked_by_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="shipment",
            name="container_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="shipment",
            name="delivery_note_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="shipment",
            name="inspection_remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="qc_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PASSED", "Passed"),
                    ("PASSED_WITH_REJECTIONS", "Passed with Rejections"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="supplier_invoice_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="shipment",
            name="warehouse",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="shipmentitem",
            name="rack",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipment_items",
                to="inventory.rack",
            ),
        ),
        migrations.AddField(
            model_name="shipmentitem",
            name="vat_percentage",
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING", "Pending"),
                    ("IN_TRANSIT", "In Transit"),
                    ("CUSTOMS_HOLD", "Customs Hold"),
                    ("DELIVERED", "Delivered"),
                    ("RECEIVED", "Received"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="DRAFT",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="shipmentitem",
            name="condition",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("USED", "Used"),
                    ("REFURBISHED", "Refurbished"),
                    ("DAMAGED", "Damaged"),
                ],
                default="NEW",
                max_length=20,
            ),
        ),
    ]
