# Generated by Django 5.2.16 on 2026-07-23 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
        ("inventory", "0010_stockadjustment_actual_quantity_counted_and_more"),
        ("purchases", "0001_initial"),
        (
            "suppliers",
            "0002_alter_supplier_options_supplier_account_holder_name_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goodsreceivednote",
            options={"ordering": ["-received_date", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="purchaseorder",
            options={"ordering": ["-order_date", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="supplierbill",
            options={"ordering": ["-bill_date", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="supplierpayment",
            options={"ordering": ["-payment_date", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="supplierreturn",
            options={"ordering": ["-return_date", "-id"]},
        ),
        migrations.RemoveField(
            model_name="supplierpayment",
            name="supplier_bill",
        ),
        migrations.AddField(
            model_name="goodsreceiveditem",
            name="quality_status",
            field=models.CharField(
                choices=[
                    ("QC_PASSED", "QC Passed"),
                    ("PARTIAL_ACCEPT", "Partial Accept"),
                    ("QC_REJECTED", "QC Rejected"),
                ],
                default="QC_PASSED",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiveditem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceivednote",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="grn/"),
        ),
        migrations.AddField(
            model_name="goodsreceivednote",
            name="warehouse_location",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="shipping_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="supplier_reference",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="supplierbill",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="supplier_bills/"),
        ),
        migrations.AddField(
            model_name="supplierbill",
            name="grn",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="purchases.goodsreceivednote",
            ),
        ),
        migrations.AddField(
            model_name="supplierbill",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="supplierbill",
            name="supplier_invoice_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="supplierbill",
            name="vat_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="supplierpayment",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="supplier_payments/"
            ),
        ),
        migrations.AddField(
            model_name="supplierpayment",
            name="paid_from",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING_APPROVAL", "Pending Approval"),
                    ("APPROVED", "Approved"),
                    ("PARTIALLY_RECEIVED", "Partially Received"),
                    ("RECEIVED", "Received"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="DRAFT",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="PurchaseExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expense_number", models.CharField(max_length=50, unique=True)),
                ("description", models.CharField(max_length=250)),
                ("category", models.CharField(max_length=100)),
                ("expense_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("vendor_name", models.CharField(blank=True, max_length=200)),
                ("payment_method", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("PAID", "Paid"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                (
                    "receipt",
                    models.FileField(
                        blank=True, null=True, upload_to="purchase_expenses/"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_purchase_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_records",
                        to="branches.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="suppliers.supplier",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-expense_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SupplierReturnItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "line_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("reason", models.CharField(blank=True, max_length=200)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.product",
                    ),
                ),
                (
                    "supplier_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="purchases.supplierreturn",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.productvariant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VendorCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("credit_number", models.CharField(max_length=50, unique=True)),
                ("credit_date", models.DateField()),
                ("reason", models.CharField(max_length=200)),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "applied_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "remaining_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("OPEN", "Open"),
                            ("PARTIALLY_APPLIED", "Partially Applied"),
                            ("APPLIED", "Applied"),
                            ("VOID", "Void"),
                        ],
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="vendor_credits/"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("approval_date", models.DateField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_vendor_credits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_records",
                        to="branches.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="suppliers.supplier",
                    ),
                ),
                (
                    "supplier_return",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="purchases.supplierreturn",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-credit_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="VendorCreditApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_applications",
                        to="purchases.supplierbill",
                    ),
                ),
                (
                    "vendor_credit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="purchases.vendorcredit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplierPaymentAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_allocations",
                        to="purchases.supplierbill",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="purchases.supplierpayment",
                    ),
                ),
            ],
            options={
                "unique_together": {("payment", "bill")},
            },
        ),
    ]
