# Generated by Django 5.2.16 on 2026-07-23 19:36

import apps.purchases.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_stockadjustment_actual_quantity_counted_and_more"),
        ("purchases", "0002_alter_goodsreceivednote_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goodsreceiveditem",
            name="rack_location",
        ),
        migrations.RemoveField(
            model_name="goodsreceivednote",
            name="attachment",
        ),
        migrations.AddField(
            model_name="goodsreceiveditem",
            name="rack",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grn_items",
                to="inventory.rack",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceivednote",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="currency",
            field=models.CharField(default="AED", max_length=5),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="other_charges",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="terms_conditions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="vat_percentage",
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
        migrations.AlterField(
            model_name="goodsreceiveditem",
            name="quality_status",
            field=models.CharField(
                choices=[
                    ("QC_PASSED", "QC Passed"),
                    ("PARTIAL_ACCEPT", "Partial Receipt"),
                    ("QC_REJECTED", "QC Flagged"),
                ],
                default="QC_PASSED",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="goodsreceivednote",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grns",
                to="purchases.purchaseorder",
            ),
        ),
        migrations.AlterField(
            model_name="goodsreceivednote",
            name="received_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_grns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="goodsreceivednote",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("CONFIRMED", "Confirmed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="DRAFT",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="GRNAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.purchases.models.grn_attachment_path
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("file_size", models.PositiveBigIntegerField(default=0)),
                ("content_type", models.CharField(blank=True, max_length=120)),
                (
                    "grn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="purchases.goodsreceivednote",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_grn_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
