# Generated by Django 5.2.16 on 2026-07-24 04:39

import apps.purchases.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
        ("finance", "0001_initial"),
        ("inventory", "0010_stockadjustment_actual_quantity_counted_and_more"),
        ("purchases", "0003_remove_goodsreceiveditem_rack_location_and_more"),
        ("suppliers", "0003_supplierdocument"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierBillAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.purchases.models.supplier_bill_attachment_path
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("file_size", models.PositiveBigIntegerField(default=0)),
                ("content_type", models.CharField(blank=True, max_length=120)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupplierBillItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("received_quantity", models.PositiveIntegerField()),
                ("bill_quantity", models.PositiveIntegerField()),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "vat_percentage",
                    models.DecimalField(decimal_places=2, default=5, max_digits=5),
                ),
                (
                    "vat_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "line_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplierPaymentAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.purchases.models.supplier_payment_attachment_path
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("file_size", models.PositiveBigIntegerField(default=0)),
                ("content_type", models.CharField(blank=True, max_length=120)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="supplierpaymentallocation",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="supplierbill",
            name="attachment",
        ),
        migrations.RemoveField(
            model_name="supplierbill",
            name="payment_status",
        ),
        migrations.RemoveField(
            model_name="supplierpayment",
            name="attachment",
        ),
        migrations.RemoveField(
            model_name="supplierpayment",
            name="paid_by",
        ),
        migrations.RemoveField(
            model_name="supplierpayment",
            name="paid_from",
        ),
        migrations.AddField(
            model_name="supplierbill",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supplierbill",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_supplier_bills",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="supplierbill",
            name="currency",
            field=models.CharField(default="AED", max_length=5),
        ),
        migrations.AddField(
            model_name="supplierbill",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="supplierbill",
            name="match_status",
            field=models.CharField(
                choices=[("UNMATCHED", "Unmatched"), ("MATCHED", "Matched")],
                default="UNMATCHED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="supplierbill",
            name="payment_terms_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="supplierbill",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("UNMATCHED", "Unmatched"),
                    ("UNPAID", "Unpaid"),
                    ("PARTIALLY_PAID", "Partially Paid"),
                    ("PAID", "Paid"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="DRAFT",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="supplierpayment",
            name="bank_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplier_payments",
                to="finance.bankaccount",
            ),
        ),
        migrations.AddField(
            model_name="supplierpayment",
            name="cash_register",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplier_payments",
                to="finance.cashregister",
            ),
        ),
        migrations.AddField(
            model_name="supplierpayment",
            name="cheque_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supplierpayment",
            name="cheque_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="supplierbill",
            name="bill_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="supplierbill",
            name="grn",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplier_bills",
                to="purchases.goodsreceivednote",
            ),
        ),
        migrations.AlterField(
            model_name="supplierbill",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplier_bills",
                to="purchases.purchaseorder",
            ),
        ),
        migrations.AlterField(
            model_name="supplierbill",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplier_bills",
                to="suppliers.supplier",
            ),
        ),
        migrations.AlterField(
            model_name="supplierbill",
            name="supplier_invoice_number",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="supplierbill",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="supplierpayment",
            name="payment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="supplierpayment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("BANK_TRANSFER", "Bank Transfer"),
                    ("CHEQUE", "Cheque"),
                    ("CASH", "Cash"),
                    ("CARD", "Card"),
                    ("OTHER", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="supplierpayment",
            name="reference_number",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="supplierpayment",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplier_payments",
                to="suppliers.supplier",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierbill",
            constraint=models.UniqueConstraint(
                fields=("supplier", "supplier_invoice_number"),
                name="unique_supplier_invoice_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierpaymentallocation",
            constraint=models.UniqueConstraint(
                fields=("payment", "bill"), name="unique_payment_bill_allocation"
            ),
        ),
        migrations.AddField(
            model_name="supplierbillattachment",
            name="bill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="purchases.supplierbill",
            ),
        ),
        migrations.AddField(
            model_name="supplierbillattachment",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_supplier_bill_attachments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="supplierbillitem",
            name="bill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="purchases.supplierbill",
            ),
        ),
        migrations.AddField(
            model_name="supplierbillitem",
            name="grn_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bill_items",
                to="purchases.goodsreceiveditem",
            ),
        ),
        migrations.AddField(
            model_name="supplierbillitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.product"
            ),
        ),
        migrations.AddField(
            model_name="supplierbillitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="supplierpaymentattachment",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="purchases.supplierpayment",
            ),
        ),
        migrations.AddField(
            model_name="supplierpaymentattachment",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_supplier_payment_attachments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
