# Generated by Django 5.2.16 on 2026-07-24 05:51

import apps.purchases.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0004_supplierbillattachment_supplierbillitem_and_more"),
        ("suppliers", "0003_supplierdocument"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierreturn",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supplierreturn",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_supplier_returns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="supplierreturn",
            name="details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supplierreturn",
            name="resolution",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUPPLIER_CREDIT_NOTE", "Supplier credit note"),
                    ("ADJUST_NEXT_BILL", "Adjust next bill"),
                ],
                max_length=40,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="supplierreturn",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supplierreturn",
            name="vendor_credit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_supplier_returns",
                to="purchases.vendorcredit",
            ),
        ),
        migrations.AddField(
            model_name="supplierreturnitem",
            name="grn_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplier_return_items",
                to="purchases.goodsreceiveditem",
            ),
        ),
        migrations.AddField(
            model_name="supplierreturnitem",
            name="received_quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="goodsreceivednote",
            name="received_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="order_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="supplierbill",
            name="supplier_invoice_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="supplierpayment",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="supplierpayment",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BANK_TRANSFER", "Bank Transfer"),
                    ("CHEQUE", "Cheque"),
                    ("CASH", "Cash"),
                    ("CARD", "Card"),
                    ("OTHER", "Other"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="supplierpaymentattachment",
            name="content_type",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="supplierpaymentattachment",
            name="file_size",
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="supplierpaymentattachment",
            name="original_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="supplierreturn",
            name="grn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplier_returns",
                to="purchases.goodsreceivednote",
            ),
        ),
        migrations.AlterField(
            model_name="supplierreturn",
            name="reason",
            field=models.CharField(
                choices=[
                    ("DAMAGED_IN_TRANSIT", "Damaged in transit"),
                    ("QUALITY_ISSUE", "Quality issue"),
                    ("WRONG_ITEM", "Wrong item shipped"),
                    ("EXCESS_QUANTITY", "Excess quantity"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="supplierreturn",
            name="return_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="supplierreturn",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING_APPROVAL", "Pending Approval"),
                    ("APPROVED", "Approved"),
                    ("CREDIT_ISSUED", "Credit Issued"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="DRAFT",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="supplierreturn",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplier_returns",
                to="suppliers.supplier",
            ),
        ),
        migrations.CreateModel(
            name="SupplierReturnAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.purchases.models.supplier_return_attachment_path
                    ),
                ),
                (
                    "original_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("file_size", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "content_type",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "supplier_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="purchases.supplierreturn",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_supplier_return_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
