# Generated by Django 5.2.16 on 2026-07-24 06:49

import apps.purchases.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0005_supplierreturn_approved_at_and_more"),
        ("suppliers", "0003_supplierdocument"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorCreditAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.purchases.models.vendor_credit_attachment_path
                    ),
                ),
                (
                    "original_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("file_size", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "content_type",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VendorCreditItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("gl_account", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=1,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "tax_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=5, null=True
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="vendorcreditapplication",
            old_name="applied_at",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="vendorcredit",
            name="attachment",
        ),
        migrations.AddField(
            model_name="vendorcredit",
            name="currency",
            field=models.CharField(blank=True, default="AED", max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="vendorcredit",
            name="internal_memo",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendorcredit",
            name="posted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendorcredit",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vendor_credits",
                to="purchases.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="vendorcredit",
            name="subtotal",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="vendorcredit",
            name="supplier_bill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vendor_credits",
                to="purchases.supplierbill",
            ),
        ),
        migrations.AddField(
            model_name="vendorcredit",
            name="tax_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="vendorcredit",
            name="void_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendorcredit",
            name="voided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendorcreditapplication",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="vendorcredit",
            name="applied_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="vendorcredit",
            name="credit_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vendorcredit",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vendorcredit",
            name="reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RETURN", "Return"),
                    ("DAMAGED_GOODS", "Damaged goods"),
                    ("OVERBILLING", "Overbilling"),
                    ("PRICE_ADJUSTMENT", "Price adjustment"),
                    ("FREIGHT_ADJUSTMENT", "Freight adjustment"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=40,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vendorcredit",
            name="reference_number",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="vendorcredit",
            name="remaining_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="vendorcredit",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DRAFT", "Draft"),
                    ("OPEN", "Open"),
                    ("PARTIALLY_APPLIED", "Partially Applied"),
                    ("FULLY_APPLIED", "Fully Applied"),
                    ("VOID", "Void"),
                ],
                default="DRAFT",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vendorcredit",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vendor_credits",
                to="suppliers.supplier",
            ),
        ),
        migrations.AlterField(
            model_name="vendorcredit",
            name="supplier_return",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vendor_credits",
                to="purchases.supplierreturn",
            ),
        ),
        migrations.AlterField(
            model_name="vendorcredit",
            name="total_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="vendorcreditapplication",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="vendorcreditapplication",
            name="bill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vendor_credit_applications",
                to="purchases.supplierbill",
            ),
        ),
        migrations.AddConstraint(
            model_name="vendorcreditapplication",
            constraint=models.UniqueConstraint(
                fields=("vendor_credit", "bill"),
                name="unique_vendor_credit_bill_application",
            ),
        ),
        migrations.AddField(
            model_name="vendorcreditattachment",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_vendor_credit_attachments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vendorcreditattachment",
            name="vendor_credit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="purchases.vendorcredit",
            ),
        ),
        migrations.AddField(
            model_name="vendorcredititem",
            name="vendor_credit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="purchases.vendorcredit",
            ),
        ),
    ]
