# Generated by Django 5.2.16 on 2026-07-24 09:34

import apps.purchases.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
        ("purchases", "0006_vendorcreditattachment_vendorcredititem_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseexpense",
            name="receipt",
        ),
        migrations.RemoveField(
            model_name="purchaseexpense",
            name="supplier",
        ),
        migrations.AddField(
            model_name="purchaseexpense",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaseexpense",
            name="bank_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_expenses",
                to="finance.bankaccount",
            ),
        ),
        migrations.AddField(
            model_name="purchaseexpense",
            name="cash_register",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_expenses",
                to="finance.cashregister",
            ),
        ),
        migrations.AddField(
            model_name="purchaseexpense",
            name="reference_number",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="purchaseexpense",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaseexpense",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rejected_purchase_expenses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchaseexpense",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseexpense",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="purchaseexpense",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RENT_UTILITIES", "Rent & Utilities"),
                    ("OFFICE", "Office"),
                    ("TRANSPORT", "Transport"),
                    ("MAINTENANCE", "Maintenance"),
                    ("MARKETING", "Marketing"),
                    ("PROFESSIONAL_FEES", "Professional Fees"),
                    ("TRAVEL", "Travel"),
                    ("MISCELLANEOUS", "Miscellaneous"),
                ],
                max_length=40,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseexpense",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseexpense",
            name="expense_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseexpense",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseexpense",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BANK_TRANSFER", "Bank Transfer"),
                    ("CHEQUE", "Cheque"),
                    ("CASH", "Cash"),
                    ("CARD", "Company Card"),
                    ("PETTY_CASH", "Petty Cash"),
                    ("OTHER", "Other"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseexpense",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("PAID", "Paid"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseexpense",
            name="vendor_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name="PurchaseExpenseAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.purchases.models.purchase_expense_attachment_path
                    ),
                ),
                (
                    "original_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("file_size", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "content_type",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="purchases.purchaseexpense",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_purchase_expense_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
