# Generated by Django 5.2.16 on 2026-07-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0007_remove_purchaseexpense_receipt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="po_number",
            field=models.CharField(
                blank=True, editable=False, max_length=50, unique=True
            ),
        ),
    ]
