# Generated by Django 5.2.16 on 2026-07-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0008_alter_purchaseorder_po_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="po_number",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
