# Generated by Django 5.2.16 on 2026-07-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0009_alter_purchaseorder_po_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseExpenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("code", models.SlugField(max_length=60, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
