# Generated by Django 5.2.16 on 2026-07-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0010_purchaseexpensecategory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PurchaseExpenseCategory",
        ),
        migrations.AlterModelOptions(
            name="purchaseorder",
            options={
                "ordering": ["-order_date", "-id"],
                "permissions": [
                    ("create_restricted_purchase", "Can create restricted purchases"),
                    ("view_restricted_purchase", "Can view restricted purchases"),
                ],
            },
        ),
        migrations.AddField(
            model_name="goodsreceiveditem",
            name="regular_accepted_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="goodsreceiveditem",
            name="regular_received_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="goodsreceiveditem",
            name="rejected_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="goodsreceiveditem",
            name="restricted_accepted_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="goodsreceiveditem",
            name="restricted_received_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="received_regular_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="received_restricted_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="regular_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="restricted_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="tax_treatment",
            field=models.CharField(
                choices=[
                    ("STANDARD_VAT", "Standard VAT"),
                    ("ZERO_RATED", "Zero Rated"),
                    ("EXEMPT", "Exempt"),
                    ("NON_TAXABLE", "Non Taxable"),
                ],
                default="STANDARD_VAT",
                max_length=30,
            ),
        ),
    ]
