# Generated by Django 5.2.16 on 2026-08-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0011_delete_purchaseexpensecategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierreturnitem",
            name="regular_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="supplierreturnitem",
            name="restricted_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="supplierreturnitem",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
