# Generated by Django 5.2.16 on 2026-08-06 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0012_supplierreturnitem_regular_quantity_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchaseorder",
            options={"ordering": ["-order_date", "-id"]},
        ),
        migrations.RemoveField(
            model_name="goodsreceiveditem",
            name="regular_accepted_quantity",
        ),
        migrations.RemoveField(
            model_name="goodsreceiveditem",
            name="regular_received_quantity",
        ),
        migrations.RemoveField(
            model_name="goodsreceiveditem",
            name="restricted_accepted_quantity",
        ),
        migrations.RemoveField(
            model_name="goodsreceiveditem",
            name="restricted_received_quantity",
        ),
        migrations.RemoveField(
            model_name="purchaseorderitem",
            name="received_regular_quantity",
        ),
        migrations.RemoveField(
            model_name="purchaseorderitem",
            name="received_restricted_quantity",
        ),
        migrations.RemoveField(
            model_name="purchaseorderitem",
            name="regular_quantity",
        ),
        migrations.RemoveField(
            model_name="purchaseorderitem",
            name="restricted_quantity",
        ),
        migrations.RemoveField(
            model_name="supplierreturnitem",
            name="regular_quantity",
        ),
        migrations.RemoveField(
            model_name="supplierreturnitem",
            name="restricted_quantity",
        ),
    ]
