# Generated by Django 5.2.16 on 2026-08-06 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
        ("inventory", "0018_alter_product_compatible_models"),
        ("purchases", "0014_supplierpayment_paid_by"),
        (
            "suppliers",
            "0004_supplier_branch_alter_supplier_payment_terms_days_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supplierreturnitem",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="supplierreturn",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="supplierreturn",
            name="vat_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="supplierreturnitem",
            name="tax_treatment",
            field=models.CharField(
                choices=[
                    ("STANDARD_VAT", "Standard VAT"),
                    ("ZERO_VAT", "Zero VAT"),
                    ("NON_VAT", "Non-VAT"),
                ],
                default="STANDARD_VAT",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="supplierreturnitem",
            name="vat_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="supplierreturnitem",
            name="vat_percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddIndex(
            model_name="supplierreturn",
            index=models.Index(
                fields=["supplier", "status"], name="purchases_s_supplie_eac0aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierreturn",
            index=models.Index(
                fields=["branch", "return_date"], name="purchases_s_branch__849b77_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierreturn",
            index=models.Index(fields=["grn"], name="purchases_s_grn_id_ac8e65_idx"),
        ),
        migrations.AddIndex(
            model_name="supplierreturnitem",
            index=models.Index(
                fields=["supplier_return"], name="purchases_s_supplie_d74ba6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierreturnitem",
            index=models.Index(
                fields=["grn_item"], name="purchases_s_grn_ite_df6065_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierreturnitem",
            index=models.Index(
                fields=["product", "variant"], name="purchases_s_product_3a5ecd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierreturnitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0)),
                name="supplier_return_item_quantity_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierreturnitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", 0)),
                name="supplier_return_item_unit_price_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierreturnitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("vat_percentage__gte", 0)),
                name="supplier_return_item_vat_percentage_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierreturnitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("vat_amount__gte", 0)),
                name="supplier_return_item_vat_amount_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierreturnitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("line_total__gte", 0)),
                name="supplier_return_item_line_total_gte_0",
            ),
        ),
    ]
