# Generated by Django 5.2.16 on 2026-08-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0015_alter_supplierreturnitem_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendorcredit",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING", "Pending Approval"),
                    ("APPROVED", "Approved"),
                    ("OPEN", "Open"),
                    ("PARTIALLY_APPLIED", "Partially Applied"),
                    ("FULLY_APPLIED", "Fully Applied"),
                    ("VOID", "Void"),
                ],
                default="DRAFT",
                max_length=30,
                null=True,
            ),
        ),
    ]
