# Generated by Django 5.2.17 on 2026-08-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0016_alter_vendorcredit_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplierpayment",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BANK_TRANSFER", "Bank Transfer"),
                    ("CHEQUE", "Cheque"),
                    ("CASH", "Cash"),
                    ("CARD", "Card"),
                    ("ONLINE", "Online Payment"),
                    ("OTHER", "Other"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
