from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = [("branches", "0001_initial"), ("hrms", "0001_initial"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name="Vehicle", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("vehicle_code", models.CharField(max_length=40, unique=True)), ("make", models.CharField(max_length=80)), ("model", models.CharField(max_length=80)), ("registration_number", models.CharField(max_length=60, unique=True)), ("vehicle_type", models.CharField(blank=True, max_length=50)), ("year", models.PositiveIntegerField(blank=True, null=True)), ("odometer_km", models.PositiveIntegerField(default=0)), ("service_due_km", models.PositiveIntegerField(blank=True, null=True)), ("fuel_type", models.CharField(blank=True, max_length=30)), ("status", models.CharField(choices=[("AVAILABLE", "Available"), ("OUT", "Out"), ("SERVICE", "In Service"), ("INACTIVE", "Inactive")], default="AVAILABLE", max_length=20)), ("notes", models.TextField(blank=True)), ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="fleet_vehicles", to="branches.branch"))], options={"ordering": ["make", "model", "registration_number"]}),
        migrations.CreateModel(name="VehicleTrip", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("checkout_at", models.DateTimeField()), ("expected_return_at", models.DateTimeField(blank=True, null=True)), ("actual_return_at", models.DateTimeField(blank=True, null=True)), ("starting_odometer_km", models.PositiveIntegerField()), ("ending_odometer_km", models.PositiveIntegerField(blank=True, null=True)), ("fuel_level_out", models.CharField(choices=[("FULL", "Full"), ("THREE_QUARTER", "3/4"), ("HALF", "1/2"), ("QUARTER", "1/4"), ("LOW", "Low")], default="FULL", max_length=20)), ("fuel_level_return", models.CharField(blank=True, choices=[("FULL", "Full"), ("THREE_QUARTER", "3/4"), ("HALF", "1/2"), ("QUARTER", "1/4"), ("LOW", "Low")], max_length=20)), ("destination", models.CharField(blank=True, max_length=255)), ("purpose", models.CharField(max_length=255)), ("departure_notes", models.TextField(blank=True)), ("return_notes", models.TextField(blank=True)), ("parking_location", models.CharField(blank=True, max_length=150)), ("expense_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)), ("receipt", models.FileField(blank=True, null=True, upload_to="fleet/receipts/")), ("status", models.CharField(choices=[("ACTIVE", "Active"), ("RETURNED", "Returned"), ("CANCELLED", "Cancelled")], default="ACTIVE", max_length=20)), ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approved_vehicle_trips", to=settings.AUTH_USER_MODEL)), ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="fleet_trips", to="branches.branch")), ("driver", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="vehicle_trips", to="hrms.employee")), ("vehicle", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="trips", to="fleet.vehicle"))], options={"ordering": ["-checkout_at"]}),
    ]
