# Generated by Django 5.2.16 on 2026-07-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit_logs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("view_complete_records", "Can view complete audit records")
                ],
            },
        ),
        migrations.AddField(
            model_name="auditlog",
            name="after_values",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="approval_reference",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="before_values",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="role",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
    ]
